openmrs/openmrs-contrib-android-client

- .gitignore
This should fix the majority of [AC-88](https://issues.openmrs.org/browse/AC-88), although I didn't add the support library jars. Not sure that we should add those in, what do you think?
> [AC-88] Add Eclipse files to .gitignore

- openmrs-client/src/main/java/org/openmrs/mobile/activities/SettingsActivity.java
- openmrs-client/src/main/res/values/styles_openmrs.xml
Back button functionality on the settings activity was missing to navigate back to home screen via action bar.This has been resolved.
@rkorytkowski please review my PR.
> Fix for AC-144 Back button functionality on the settings activity has been provided 

- odkcollect/src/main/java/org/odk/collect/android/views/HierarchyElementView.java
Reverts openmrs/openmrs-contrib-android-client#116
It caused build failure at https://travis-ci.org/openmrs/openmrs-contrib-android-client/builds/111445687
> Revert "Fix AC-148 Set proper resource id at runtime"

- openmrs-client/src/main/res/values/strings.xml
Previously message text in the dialog was: There are already active visit. Synchronize patient or close previous visit.
Now the warning/error in "ACBaseActivity.java" has been removed. We were not using the argument title declared in the function. Now the new message text in dialog box is:  There are already active visit for Bob Smith. Synchronize patient or close previous visit.
> Fixed AC-154: Corrected the string format.

- openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/adapters/PatientArrayAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/visit/FindVisitsByPatientUUIDListener.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ToastUtil.java
- openmrs-client/src/main/res/values/strings.xml
A toast would be sufficient informing download has been started and ended. It doesn't blocks the UI and is more intuitive for the user.
> Fixed AC-138: We don't have to block UI by showing a progress dialog

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Added a flag to project properties to ignore gradle version difference. Also upgraded to latest gradle distribution.
> Fix build errors due to gradle version difference

- openmrs-client/src/main/java/org/openmrs/mobile/activities/FindSyncedPatientsActivity.java
This change prevents NullPointerException when applying filter to patientIdentifier which can be null if not synchronized.
@AvijitGhosh82
> AC-193 - Minor search function bugfix

- openmrs-client/build.gradle
- openmrs-client/src/main/java/org/openmrs/mobile/api/RestServiceBuilder.java
- openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/Person.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ResourceSerializer.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/ResourceSerializerTest.java
Sooo, the first serializer didn't work at all... We've noticed that with @tmarzeion when working on changing Visit model to match retrofit. 
I have modified it now to work with all classes that are Resources. 
Here is how it works:
when you post Resource object via retrofit this custom serializer checks all declared fields. If there is a Resource with uuid set it will serialize it to uuid only. When uuid is null it will serialize full object. 
When declared field is a collection, serializer iterates through it and does the same as above. It the collection contains objects that are not Resources,  it will be serializes with default gson serializer.
@rkorytkowski @AvijitGhosh82 @tmarzeion 
What do you think about that ? 
This is made to make posting object easier. Instead writing custom …
> AC-196 fixed serializer to work with all resources

- openmrs-client/src/main/java/org/openmrs/mobile/models/PersonAddress.java
AC-265: Addresses switched when syncing patient from server
https://issues.openmrs.org/browse/AC-265
I fixed switching address in Android client.
> AC-265: Addresses switched when syncing patient from server

- openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/models/QuestionOptions.java
It is now possible to describe "allowDecimal" property in form's resource's json (default false).
When allowDecimal is disabled, question field doesn't allow to input commas.
> Added support for decimal numeric values in forms

- openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.java
- openmrs-client/src/main/res/layout/activity_dashboard.xml
- openmrs-client/src/main/res/layout/fragment_dashboard.xml
- openmrs-client/src/main/res/values/dimens.xml
I've done some layout cleanup by removing useless containers and properties in `*.xml` files.
I've managed to fix `AC-227` issue by implementing layout with better screen space management.
@rkorytkowski @ykarim @AdamGrzybkowski @lkukielka Tell me if You think that these layout changes are looking bad or something.
PS. @ykarim Could You check how does this look on SGS6 Edge+?
| API-23 FULL-HD  | API-16 LOW-RES |
| ------------- | ------------- |
| <img src="https://cloud.githubusercontent.com/assets/17570611/21424823/743b2f44-c845-11e6-878b-47d7cf253ef2.png" width="250"/>  | <img src="https://cloud.githubusercontent.com/assets/17570611/21424935/56a7775c-c846-11e6-88e9-3abde861a880.png" width="250"/>  |
| API-23 FULL-HD  | API-16 LOW-RES |
| ------------- | ------------- |
| <img …
> AC-227 - Fixed main dashboard layout

- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java
The patients' data was downloading again and again because whenever fragment resumed, presenter started and it initiates downloading. The data was also downloaded whenever the search query is empty and it is always empty when the fragment is starting.
> AC-285: Patients' data downloaded again when activity resumes

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
Now the user cannot select future dates as Date of Birth in the registration form, as they have been disabled. Here is a screen-shot
> AC-323 DatePicker prevents future dates as DOB in registration form

- openmrs-client/src/main/res/layout-land/list_visit_group.xml
Now the text size and icon size in landscape mode in 'Encounters' is consistent with the portrait mode. Here is the screen shot-
> AC-327 Fixed text size in landscape view in 'Encounters'

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
- openmrs-client/src/main/res/layout/fragment_patient_info.xml
Now when the user taps "Country" field in Register Patient the country suggestions are shown even if the user doesn't type anything.
> AC-329 List of countries don't show automatically

- appveyor.yml
For testing windows builds.
Note: Building tags is still done only via travis. This is just an extra check for non *nix systems.
> Add Appveyor.yml

- openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ForceClose.java
- openmrs-client/src/main/res/values/strings.xml
Below dialog will be displayed whenever the app is crashed.
A sample email which will be sent can be found [here](https://pastebin.com/kaKDBh4p). 
Along with this, the app logs will also be attached as a text file to the email.
> AC-403 : Feedback / Bug Report System

- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientPhotoActivity.java
Pressing the back button will return to the parent activity, i.e.
the PatientDashboardActivity.
Ref ticket: https://issues.openmrs.org/browse/AC-394
> AC-394: Add back button to PatientPhotoActivity action bar.

- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.java
**JIRA TICKET NAME:**
[AC-424:Do not require login location if no locations are configured.](https://issues.openmrs.org/browse/AC-424)
**Summary:**
Do not require login location if no locations are configured.
> AC-424:Do not require login location if no locations are configured.

- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.java
- openmrs-client/src/main/res/color/login_button.xml
- openmrs-client/src/main/res/layout/fragment_login.xml
- openmrs-client/src/main/res/values/login_button_style.xml
- openmrs-client/src/main/res/values/strings.xml
Ref ticket: https://issues.openmrs.org/browse/AC-426
With this commit, we indicate that fields are required by adding a
"Required *" label at the bottom of the form's fields. Required fields
has a matching asterisk.
This commit uses HTML formatted strings to show
the user which fields in the login form are required
to be able to login. However, the formatting doesn't
work for TextInputLayout, only for TextView. Therefore,
we toggle between setting the hint on the TextView (to
get color coding) or on the TextInputLayout (to get
floating hints).
This commit also adds some styling to the login button:
Specifically, it turns it pale, not just the background
but the text color as well until all required fields are entered.
> AC-426: Improve UI of login form

- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
- openmrs-client/src/main/res/values/strings.xml
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LoginPresenterTest.java
When a user logs in using offline mode then a toast message shows up "LoggedIn in offline mode" which is still informative but somewhat confusing. I changed it to "You are now in offline mode" whose meaning is direct and straightforward.
see https://issues.openmrs.org/browse/AC-431
> [AC-431] Make the toast mesage standard

- openmrs-client/src/main/java/org/openmrs/mobile/models/Encountercreate.java
**JIRA Issue link:**  https://issues.openmrs.org/browse/AC-446
**JIRA Summary:**
1. The variable `obscreateList` is redundant. Rather than creating a new variable, just assign value from the `gson.fromJson()` statement.
2. Also, add spaces on both sides of `equal to` in this function and the function above it.
> AC-446: Variable obscreateList is redundant

- openmrs-client/src/main/java/org/openmrs/mobile/security/SecretKeyGenerator.java
I have upgraded `bytesToHex` method to use `StringBuilder` to prevent from unecessary string copying in the for loop.
**All existing tests passed.**
https://issues.openmrs.org/browse/AC-484
> AC-484: Made SecretKeyGenerator.bytesToHex() more efficient

- openmrs-client/build.gradle
- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
- openmrs-client/src/main/res/values/strings.xml
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LoginPresenterTest.java
This PR brings several changes to the code
- User's password is not stored as a plaintext (used in offline verification), but as a bcrypt hash. It makes it not possible to steal user's password from `SharedPreferences` anymore.
- SQLite database uses a peppered bcrypt hash as its password, which is derived from user's name and password. It is not stored on the device anymore, making it impossible to steal, but generated after the user enters the password.
- When the user logs in to the same account using new password, the user is warned and the DB gets wiped (because the app just breaks when user changes the pass, doesn't matter if it's online or offline and because the new password is not sufficient for generating matching key to SQLite db). This is a temporary fix to lack of handling …
> AC-465: Encrypt database from the details derived from the username and password

- openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/NetworkUtils.java
This PR replaces `SharedPreferences.Editor.commit()` calls with `SharedPreferences.Editor.apply()` when the return value of `commit()` is ignored. It's better to use asynchronous version of the API to prevent from blocking UI thread. For more information, check out JIRA ticket below.
**All existing tests passed.**
https://issues.openmrs.org/browse/AC-493
> AC-493: Use editor.apply() instead of editor.commit()

- .travis.yml
- openmrs-client/build.gradle
This PR fixes the problem that coveralls build is not present at https://coveralls.io/github/openmrs/openmrs-contrib-android-client . I used the JaCoCo plugin instead of cobertura, as described in [this tutorial](https://jeroenmols.com/blog/2015/11/13/traviscoveralls/).
https://issues.openmrs.org/browse/AC-483
> AC-483 Adding coveralls to openmrs-contrib-anroid-client repository

- openmrs-client/src/test/java/org/openmrs/mobile/test/DBOpenHelperTest.java
I've added `DBOpenHelperTest` with some tests inside - it's also a good base for writing future tests for this class (and its parents).
*Obviously ( ͡° ͜ʖ ͡°)*, **all existing tests passed.** 
https://issues.openmrs.org/browse/GCI-286
> GCI-286: Added tests for DBOpenHelper

- .github/PULL_REQUEST_TEMPLATE.md
I've added a PR template familiar to [the one we have on openmrs-core](https://github.com/openmrs/openmrs-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md). It'll help to make PRs in this repository less messy.
JIRA Issue: https://issues.openmrs.org/browse/AC-496
> AC-496: Adding a PR template to openmrs-contrib-anroid-client repository

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientContract.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
- openmrs-client/src/main/res/values/strings.xml
When the user tries to press back while registering a patient a warning dialog is presented that if he exists the activity without completing the registration, all the entered information will be lost.
JIRA Issue: https://issues.openmrs.org/browse/AC-528
> AC-528: Warning Dialog when back pressed

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
Some minor changes to prevent crashing of app
JIRA Issue: https://issues.openmrs.org/browse/AC-522
Before
Now
> AC-522: Prevented crashing when selecting "Take a photo" option

- openmrs-client/build.gradle
- openmrs-client/proguard-rules.txt
There are multiple warnings that should be ignored with `-dontwarn` on all the dependencies that error-ed when minimizing. ([see this thread](https://exceptionshub.com/transformclassesandresourceswithproguardforrelease-failed.html) on why ProGuard is now failing) And the target SDK level should match the compile SDK version.
JIRA Issue: https://issues.openmrs.org/browse/AC-580
> AC-580: Fix ProGuard and SDK level

- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
Fixes issue of cursor going to the beginning of EditText on toggling show/hide password.
Now, the cursor stays where it was before.
JIRA Issue: https://issues.openmrs.org/browse/AC-563
**Before**
**After**
> AC 563: Show/Hide password brings cursor of EditText to beginning

- openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/services/ConceptDownloadService.java
- openmrs-client/src/main/res/values/strings.xml
Added a condition to check whether the concepts in DB are 0 and disabled the user from clicking the Download Button if this condition is true and a toast will be displayed on page load informing the user of this. Further, null checks were introduced to ConceptDownloadService class.
This is a critical bug in the Android Application
JIRA Issue: https://issues.openmrs.org/browse/AC-571
> AC-571 - Application Crashes when click download concepts

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
App now reverts back to register patient activity on clicking cancel
JIRA Issue: https://issues.openmrs.org/browse/AC-582
> AC-582 App should revert to register patient activity on clicking cancel if a duplicate patient is found

- openmrs-client/build.gradle
Removed deprecated Apache HTTP API Client library from build.gradle (app level).
JIRA Issue: https://issues.openmrs.org/browse/AC-607
> AC-607: Replace Apache HTTP API Client library

- openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/SimilarPatientsRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MergePatientsRecycleViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDashboardDetailsPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/PatientService.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/RestApi.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/retrofit/PatientApi.java
- openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientDAO.java
- openmrs-client/src/main/java/org/openmrs/mobile/databases/DBOpenHelper.java
- openmrs-client/src/main/java/org/openmrs/mobile/models/Patient.java
- openmrs-client/src/main/java/org/openmrs/mobile/models/PatientDto.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/FilterUtil.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/PatientComparator.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/PatientMerger.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/ACUnitTestBase.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/ResourceSerializerTest.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/AddEditPatientPresenterTest.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/MatchingPatientsPresenterTest.java
- openmrs-client/src/test/java/org/openmrs/mobile/utilities/DateUtilsTest.java
* Changing the relationship between `Patient` and `Person` to `is a` relationship instead of `has a` relationship.
* Details that can be updated in a patient now can be updated through a new `PatientDetails` object.
* We had a hard dependency on the backend API while updating or registering patient, It still accepts certain detail as part of `person` key. So we have exposed a `getPerson` method while making any network request.  
After this PR, `Patient` model is extending Person. From now onwards, we have to get patient details from the Patient itself instead of from Person.
patient.getPerson().getNames();
patient.getNames();
I have already run the unit test at my local machine and all are passing successfully and I also run the application on the device and it also works the expected …
> AC-480 Patient model should extend Person

- README.md
- openmrs-client/build.gradle
- openmrs-client/src/main/java/org/openmrs/mobile/api/RestServiceBuilder.java
- openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
Integrating **Android snooper** for debugging enhancement.
JIRA Issue: https://issues.openmrs.org/browse/AC-534
> AC:534 Integrating android snooper for debugging purpose.

- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
- openmrs-client/src/main/res/layout/row_find_last_viewed_patients.xml
In download patients, only the Patient ID was showing, now the name is also showing.
JIRA Issue: https://issues.openmrs.org/browse/AC-623
> AC-623: Name and other details are not showing when searching patients

- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderContract.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/MatchingProviderRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
- openmrs-client/src/main/res/layout/custom_matching_provider_alert_dialog.xml
- openmrs-client/src/main/res/layout/row_matching_provider.xml
- openmrs-client/src/main/res/layout/row_provider_details.xml
- openmrs-client/src/main/res/layout/row_provider_management.xml
- openmrs-client/src/main/res/values/strings.xml
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/AddProviderPresenterTest.java
- Added a check for matching providers
- Created an AlertDialog to show matching providers
JIRA Issue: https://issues.openmrs.org/browse/AC-625
> AC-625: Check if newly created provider is similar to an existing one

- openmrs-client/src/main/AndroidManifest.xml
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardContract.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPagerAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/patientrelationship/PatientRelationshipFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/providerrelationship/ProviderRelationshipFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
- openmrs-client/src/main/res/layout/activity_provider_dashboard.xml
- openmrs-client/src/main/res/layout/fragment_patient_relationship.xml
- openmrs-client/src/main/res/layout/fragment_provider_relationship.xml
- openmrs-client/src/main/res/layout/row_provider_management.xml
- openmrs-client/src/main/res/values/strings.xml
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderDashboardPresenterTest.java
- Added a provider dashboard
- Created a placeholder fragment for Patient-Provider relationship
- Created a placeholder fragment for Provider-Provider relationship
JIRA Issue: https://issues.openmrs.org/browse/AC-626
> AC-626: Add Provider Dashboard

- openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ImageUtils.java
Changed Tint of ImageViews in the Dashboard buttons depending on the theme set.
JIRA Issue: https://issues.openmrs.org/browse/AC-627
> AC-627: Change ImageView color depending upon theme

- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientVitalsFragment.java
Removed the line that set TextView text to "None". Only visibility needed to be checked. The text was already set.
JIRA Issue: https://issues.openmrs.org/browse/AC-619
> AC-619: Fix window leakage error while viewing patient details

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientChartsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/diagnosis/PatientDiagnosisFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientVisitsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientVitalsFragment.java
In order to bypass the the static memory leak, I created instance variables in each of the other classes that used LinearLayouts and used that to access the methods from the PatientsDashboardActivity class.
../../src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java:61: Do not place Android context classes in static fields; this is a memory leak
- [x ] My pull request only contains **ONE single commit**
- [ x] All new and existing **tests passed**.
- [ x] My pull request is **based on the latest changes** of the master branch.
> GCI-340 Android Client: Fix this Static field leak

- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LoginPresenterTest.java
Upon investigation, I have discovered that when signing in to OpenMRS AC for the first time, `FormListService` is not called due to the user not being logged in. After the user authenticates successfully, they cannot use any forms, since they have not been downloaded. I have fixed this by calling `FormListService` upon user authentication in `LoginFragment`.
JIRA Issue: https://issues.openmrs.org/browse/AC-530
> AC-530 The form edit button in Vitals page is not working

- openmrs-client/src/main/res/layout/activity_provider_dashboard.xml
- openmrs-client/src/main/res/layout/fragment_patient_relationship.xml
- openmrs-client/src/main/res/layout/fragment_provider_relationship.xml
- openmrs-client/src/main/res/layout/row_provider_details.xml
- openmrs-client/src/main/res/values/strings.xml
Converted all hardcoded strings to String Resources, so that the app can have support for multiple languages in the future.
GCI Task: [Android Client: Convert Hardcoded Strings to String Resources](https://codein.withgoogle.com/dashboard/task-instances/6652232368390144/)
[AC-441](https://issues.openmrs.org/browse/AC-441)
> [AC-441] Convert Hardcoded Strings to String Resources

- openmrs-client/build.gradle
I added debugImplementation of leak canary in the builld.gradlefile.
JIRA Issue: https://issues.openmrs.org/browse/AC-633
> [AC-633] Integrate leak canary to debug version

- openmrs-client/build.gradle
- openmrs-client/src/main/AndroidManifest.xml
- openmrs-client/src/main/java/org/openmrs/mobile/activities/SplashActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
- openmrs-client/src/main/res/anim/splash_screen_logo_anim.xml
- openmrs-client/src/main/res/layout/activity_splash.xml
Added a Splash Screen to the app, with an animation.
JIRA Issue: https://issues.openmrs.org/browse/AC-636
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/6153655376412672/
> [AC-636] Add a Splash Screen

- openmrs-client/src/main/res/layout-land/list_visit_group.xml
- openmrs-client/src/main/res/layout-large/list_visit_group.xml
- openmrs-client/src/main/res/layout/list_visit_group.xml
Wrap Parent layout to match text size in charts list and setting horizontal divider height to match parent.
JIRA Issue: https://issues.openmrs.org/browse/AC-560
> AC-560 Wrap Parent layout to match text size in charts list

- openmrs-client/src/main/res/layout/fragment_add_provider.xml
- openmrs-client/src/main/res/layout/fragment_patient_info.xml
- As some of the important input fields were having just a text input in lowercase, such as '**City**','**First Name**' etc.,an input of capitalising the the first letter needs to be added as these fields are of high priority.
- Changed input type from `android:inputType="text"` to `android:inputType="textCapWords" ` which was missing for some important input fields.
JIRA Issue: https://issues.openmrs.org/browse/AC-638
> AC-638 Adding inputType for capitalising the first letter

- README.md
Added the Contribution Guidelines to README.md
JIRA Issue: https://issues.openmrs.org/browse/AC-649
> [AC-649] Add Contribution Guidelines to README

- openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/PatientRoomDAOTest.java
- openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientRoomDAO.java
- openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabase.java
Updated PatientDAO for room including six tests
JIRA Issue: https://issues.openmrs.org/browse/AC-476
> AC-476 Updated PatientDAO for room including six tests

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
- openmrs-client/src/main/res/layout/fragment_patient_info.xml
In XML fragment_patient_info country picker & state autocomplete aligned 
In AddEditPatientActivity alert dialog box buttons alignment corrected Positive Button -> Neutral Button
JIRA Issue: https://issues.openmrs.org/browse/AC-670
> AC-670 UI fixes in Register Patient Activity

- openmrs-client/src/main/res/color/login_button.xml
- openmrs-client/src/main/res/color/login_button_background.xml
- openmrs-client/src/main/res/layout/fragment_dialog_layout.xml
- openmrs-client/src/main/res/layout/fragment_login.xml
- openmrs-client/src/main/res/layout/fragment_settings.xml
- openmrs-client/src/main/res/values-v21/login_button_style.xml
- openmrs-client/src/main/res/values/login_button_style.xml
I've modified the login_button_color.xml file to adapt it to changes in the background as well.
I've changed the fragment_dialog_layout.xml so that all the custom dialogues now gives a better visual appeal to the app.
JIRA Issue: https://issues.openmrs.org/browse/AC-591
> AC-591 Improved UI of login button and FragmentDialogue buttons

- openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
Alert dialog was not dismissed when activity got destroyed so there was a leak. I have dismissed the alert dialog in the onDestroy method of the activity.
JIRA Issue: https://issues.openmrs.org/browse/AC-714
> AC-714 - AlertDialog not canceled on activity destroyed

- openmrs-client/src/main/java/org/openmrs/mobile/models/PatientDto.kt
PatientDto was not excepting the null value for the photo which I changed so it can accept.
JIRA Issue: https://issues.openmrs.org/browse/AC-743
> AC-743 NPE removed at PatientDashboard

- openmrs-client/build.gradle
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/workers/UpdateWorker.java
- openmrs-client/src/main/res/values/strings.xml
Provided a WorkManager Implementation for handling deferred updates to server after modification in the details of a patient.
1. added support for WorkManager in app level Build.gradle work_version ="2.3.3"
2. implemented worker for deferred update operations to the server.
JIRA Issue: https://issues.openmrs.org/browse/AC-732
> AC-732 : offline update bug fixed

- openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
- openmrs-client/src/main/res/values-hi/strings.xml
- openmrs-client/src/main/res/values/strings.xml
1. Added showcase view to manage providers
2. Localized the heading and title strings used in showcase views.
JIRA Issue: https://issues.openmrs.org/browse/AC-739
> AC-739 Added showcase view to manage providers

- openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
- openmrs-client/src/main/res/values/styles.xml
searchView takes up null value in dark mode of operation in absence of ActionBar,thus onCreateOptionsMenu never gets called so NPE was thrown.
JIRA Issue: https://issues.openmrs.org/browse/AC-740
> AC-740 fixed NPE at syncedPatient activity

- openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/EncounterRoomDAOTest.java
The test for `getAllEncountersByType` was completely wrong and had to do significant changes to pass this test. 
JIRA Issue: https://issues.openmrs.org/browse/AC-754
> AC-757 Fixed EncounterRoomDAO tests

- openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
1. I changed the ACBaseActivity to start settings activity for a result and checked if it results ok then 
after the settings activity returns I recreate the dashboard activity
JIRA Issue: https://issues.openmrs.org/browse/AC-745
> AC-745 fixed the transition error upon language change

- openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
Just prevented `ACBaseActivity` to check if the user is logged in or not in `SplashActivity` as it caused to trigger `Login Page` and `AppIntro` page was skipped
JIRA Issue: https://issues.openmrs.org/browse/AC-729
> AC-729 App Intro Slides are shown on second app run

- openmrs-client/src/androidTest/java/org/openmrs/mobile/test/VisitRoomDAOTest.java
JIRA Issue: https://issues.openmrs.org/browse/AC-758
> AC-758 Fixed VisitRoomDAO tests

- openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
I have extended the base application class from MultiDexApplication class.
I referred following thread https://stackoverflow.com/questions/52696574/didnt-find-class-androidx-core-content-fileprovider
JIRA Issue: https://issues.openmrs.org/browse/AC-726
> AC-726 : Rectified app crash on lower api devices

- openmrs-client/src/main/AndroidManifest.xml
Added adjustResize instead of adjustPan in windowSoftInputMode attribute for LoginActivity in manifest file.
JIRA Issue: https://issues.openmrs.org/browse/AC-768
> AC-768: Added adjustResize to avoid soft keyboard to block snackbar messages

- openmrs-client/build.gradle
- openmrs-client/src/main/java/org/openmrs/mobile/api/RestServiceBuilder.java
- openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
1. Added chucker support, all the functionality works as expected,
2. I have added that guava dependency because it resolves duplicate classes problem which I faced while making changes to the dependencies in gradle 
JIRA Issue: https://issues.openmrs.org/browse/AC-769
> AC-769 Added chucker support for API Calls

- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/retrofit/ProviderRepository.java
Corrected the ill formed provider that was being communicated to the servers earlier resulting in internal server error code ie 500 being returned.
JIRA Issue: https://issues.openmrs.org/browse/AC-771
> AC-771 fixed the ill formed provider fields

- openmrs-client/build.gradle
- openmrs-client/src/main/AndroidManifest.xml
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
1. Added the library
2. Added storage permission checks while selecting the photo from the gallery
3. Removed the code to process images from gallery and updated it with new one
JIRA Issue: https://issues.openmrs.org/browse/AC-788
> AC-788 Added crop image feature at registration screen

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsFragment.java
- openmrs-client/src/main/res/drawable/rectangle_transparent_box.xml
- openmrs-client/src/main/res/layout/activity_splash.xml
- openmrs-client/src/main/res/layout/fragment_matching_patients.xml
- openmrs-client/src/main/res/layout/fragment_patient_info.xml
- openmrs-client/src/main/res/values/strings.xml
1. Converted maximum XML to constraint layout
2. Changed UI
3. Renamed id's to so they make more sense
4. Used view binding in whole activity
5. Updated Alert dialog box
JIRA Issue: https://issues.openmrs.org/browse/AC-791
> AC-791 Updated UI of registeration screen

- openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/introduction/IntroActivity.kt
- openmrs-client/src/main/java/org/openmrs/mobile/activities/introduction/SplashActivity.kt
- openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt
- openmrs-client/src/main/res/layout/snackbar.xml
- openmrs-client/src/main/res/values-hi/strings.xml
- openmrs-client/src/main/res/values/strings.xml
1. Added snack bar **"Select Form entry from the menu"** with the action button to take you there.
2. Added snack bar **"No Forms Found, try restarting the app."** when the form list is empty.
JIRA Issue: https://issues.openmrs.org/browse/AC-794
> AC-794 Notify users when active visits or formlist pages are empty

- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardContract.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardPagerAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientAllergyFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientAllergyRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientDashboardAllergyPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/RestApi.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/AllergyRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/models/Allergen.kt
- openmrs-client/src/main/java/org/openmrs/mobile/models/Allergy.kt
- openmrs-client/src/main/java/org/openmrs/mobile/models/AllergyReaction.kt
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt
- openmrs-client/src/main/res/layout/fragment_patient_allergy.xml
- openmrs-client/src/main/res/layout/list_patient_allergy.xml
- openmrs-client/src/main/res/values-hi/strings.xml
- openmrs-client/src/main/res/values/strings.xml
- openmrs-client/src/test/java/org/openmrs/mobile/test/ACUnitTestBase.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardAllergyPresenterTest.java
1. Added new tab in the dashboard
2. Created rest calls to fetch data
3. Added kotlin data classes
4. Added an abstraction layer in presenter
5. Added appropriate tests
JIRA Issue: https://issues.openmrs.org/browse/AC-804
> AC 804 Added Allergy Tab to fetch allergies from server

- openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/VisitRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/DefaultVisitsCallback.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/VisitDashboardPresenterTest.java
1. Added the missing repository layer to the visitDashboard package where the API endpoints were directly being accessed form the presenter instead of VisitsRepository .
2. fixed broken tests due to the change
JIRA Issue: https://issues.openmrs.org/browse/AC-813
> AC-813 added elided repository layer in visitDashboard package

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayMainPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDashboardDetailsPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientDashboardVisitsPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientDashboardVitalsPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/EncounterService.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/VisitRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/workers/UpdatePatientWorker.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/DefaultResponseCallback.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/DownloadPatientCallback.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/EncounterResponseCallback.kt
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/GetVisitTypeCallback.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/LocationResponseCallback.kt
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/StartVisitResponseCallback.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/VisitsResponseCallback.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java
1. Added and fixed violations of repository layer Abstraction
2. converted callback interfaces into kotlin
3. Added default method to default interface to handle extensions gracefully without empty methods
4. renamed custom callbacks for uniformity
JIRA Issue: https://issues.openmrs.org/browse/AC-819
> AC-819 Added repository layer for formAdmission package

- openmrs-client/build.gradle
- openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
- openmrs-client/versions.gradle
1. Disabled minifyEnabled which increased app size by 3mb
2. Removed SQL-cipher which decreased app size by 5mb
JIRA Issue: https://issues.openmrs.org/browse/AC-824
> AC-824 Fixed Release version blocker

- openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json
- openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/AllergyRoomDAOTest.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardContract.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientAllergyFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientAllergyRecyclerViewAdapter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientDashboardAllergyPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/RestApi.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/AllergyRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/workers/allergy/DeleteAllergyWorker.java
- openmrs-client/src/main/java/org/openmrs/mobile/dao/AllergyRoomDAO.java
- openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
- openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/AllergyEntity.kt
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt
- openmrs-client/src/main/res/layout/list_patient_allergy.xml
- openmrs-client/src/main/res/values-hi/strings.xml
- openmrs-client/src/main/res/values/strings.xml
JIRA Issue: https://issues.openmrs.org/browse/AC-810
> AC-810 Allergy can be deleted in online/offline mode

- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/DeleteProviderWorker.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/UpdateProviderWorker.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/CustomApiCallback.java
- openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofit/PatientResponseCallback.kt
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LastViewedPatientsPresenterTest.java
1. added repository layer for lastViewedPatient package
2. added necessary changes to tests
3. Added custom callback
JIRA Issue: https://issues.openmrs.org/browse/AC-822
> AC-822 added repository layer for lastViewedPatient package

- openmrs-client/src/main/java/org/openmrs/mobile/services/ConceptDownloadService.java
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt
JIRA Issue: https://issues.openmrs.org/browse/AC-664
> AC-664 Added Notification channel for higher API levels

- openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyContract.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientAllergyFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/RestApi.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/AllergyRepository.java
- openmrs-client/src/main/java/org/openmrs/mobile/dao/AllergyRoomDAO.java
- openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.kt
- openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/AllergyEntity.kt
- openmrs-client/src/main/res/layout/fragment_allergy_info.xml
1. Since allergen is fixed once created, so haven't given option to change it
2. Added `allergenType` field in AllergyEntity
3. Created appropriate rest calls
JIRA Issue: https://issues.openmrs.org/browse/AC-811
> AC-811 Allergy can be updated as per server settings

- openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayContract.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayMainPresenter.java
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/VisitRepository.java
1. added a method for accessing the dao in the repository.
2. added repository to the presenter .
JIRA Issue: https://issues.openmrs.org/browse/AC-830
> AC-830 Added repository abstraction for formDisplay package

- openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionContract.kt
- openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionFragment.kt
- openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.kt
- openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
- openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java
We need to observe the encounter roles and locations using live data as in dark mode, activity is re-created immediately and the results cause NPE as the fragment is destroyed on which it needed to show.
JIRA Issue: https://issues.openmrs.org/browse/AC-829
> AC-829 Fixed crash at admission form by using live data

- openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListAdapter.kt
- openmrs-client/src/main/res/layout/row_patient_details.xml
JIRA Issue: https://issues.openmrs.org/browse/AC-839
> AC-839 Updated UI for form list card view

- openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MergePatientsRecycleViewAdapter.java
- openmrs-client/src/main/res/layout/fragment_dashboard.xml
- openmrs-client/src/main/res/layout/row_similar_patient.xml
Fixed the orientation of dashboard layout and alignment of text
JIRA Issue: https://issues.openmrs.org/browse/AC-734
>  AC-734 Fixed the orientation in the Dashboard layout

- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
https://user-images.githubusercontent.com/56927750/104127924-ca539680-538a-11eb-93e4-d01f57e30752.jpeg
Earlier if all the address fields were empty and someone tried to register patient, then no error message was being displayed. In this pull request I have corrected this and now if all the address fields are empty an error message is being displayed.
JIRA Issue: https://issues.openmrs.org/projects/AC/issues/AC-859
> AC-859 Displaying error if all address fields are empty

- openmrs-client/src/main/java/org/openmrs/mobile/activities/community/contact/ContactUsActivity.kt
In Contact Us activity on tapping Email Us, the user is redirected to Gmail App but the email address to whom we have to send the mail was not the company's mail id but instead the text "Email us". Now it has been corrected and the correct mail address has been added.
JIRA Issue: https://issues.openmrs.org/browse/AC-862
> AC-862 Corrected mail recipient in the contact us page

- openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.kt
- openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt
In the settings activity initially language codes were used. They are now replaced with the full language names.
JIRA Issue: https://issues.openmrs.org/browse/AC-869
> AC-869 Replaced language codes with their full names in Settings Activity.

- openmrs-client/build.gradle
viewBinding.enabled was obsolete and it was to be removed in Android Gradle version 5.0. So I replaced that with buildFeatures.viewBinding
JIRA Issue: https://issues.openmrs.org/browse/AC-945
> AC-945 Replaced ViewBinding.enabled with build features.viewBinding

- openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
- openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientAllergyFragment.java
- openmrs-client/src/main/res/values/styles_openmrs.xml
The color of buttons of edit text was not visible clearly in the dark mode earlier. Changed them to a color visible in both light and dark mode.
JIRA Issue: https://issues.openmrs.org/browse/AC-961
> AC-961 Changed color of buttons of Alert Dialog

- openmrs-client/build.gradle
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
---
This is a security fix for a high-severity vulnerability in your [Gradle](https://gradle.org/) `build.gradle` file(s).
The build files indicate that this project is resolving dependencies over HTTP instead of HTTPS.
This leaves your build vulnerable to allowing a [Man in the Middle](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) (MITM) attackers to execute arbitrary code on your or your computer or CI/CD system.
This vulnerability has a CVSS v3.0 Base Score of …
> [SECURITY] Use HTTPS to resolve dependencies in Gradle Build

- openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
- openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
- openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/ObservationRepositoryTest.kt
- openmrs-android-sdk/src/test/resources/mocked_responses/ObservationRepository/ObservationPost-success.json
- openmrs-android-sdk/src/test/resources/mocked_responses/ObservationRepository/ObservationResources-Get.json
- Added Unit tests for Observation Repository
JIRA Issue: https://issues.openmrs.org/browse/AC-1092
> AC-1092: Add Tests for Observation Repository
