openmrs/openmrs-contrib-android-client

README.md
src/org/openmrs/mobile/activities/FindPatientsActivity.java
src/org/openmrs/mobile/activities/FindPatientsSearchActivity.java
src/org/openmrs/mobile/activities/PatientDashboardActivity.java
src/org/openmrs/mobile/activities/fragments/FindPatientLastViewedFragment.java
src/org/openmrs/mobile/net/BaseManager.java
src/org/openmrs/mobile/net/FindPatientsManager.java

* I changed FindPatientsManager class to use Response.Listener implementation created in Activity, that uses particular method of FindPatientsManager,
* I moved url's to static variables and renamed few others to work out with our convention.

105: Refactored main issues + minor fix

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/LoginActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/PatientArrayAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/net/AuthorizationManager.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/URLValidator.java

Patient list loading crashed if the birthday was null (AC-147)
The app did not connect to server if user did not explicitly mention http or https (AC-146)
Both fixed.

Fix AC-146 and AC-147

---

openmrs-client/src/main/java/org/openmrs/mobile/net/helpers/FindPatientsHelper.java

This is an implementation of bug filed over at https://issues.openmrs.org/browse/AC-145

Added http url addressing for query parameter

---

openmrs-client/src/main/res/layout/openmrs_edit_text_field.xml

I created an [issue-AC-149](https://issues.openmrs.org/browse/AC-149) on JIRA and this is the pull request for the issue.
Please let me know if any improvement needed.

AC-149: Typed URL not visible on freshly installed app

---

openmrs-client/src/main/java/org/openmrs/mobile/listeners/forms/AvailableFormsListListener.java
openmrs-client/src/main/res/values/strings.xml

Fixed AC-132 and Fixed AC-155

---

openmrs-client/src/main/java/org/openmrs/mobile/models/mappers/VisitMapper.java

A node(location) in the fetched [JSON](https://docs.google.com/document/d/1GLUcstfogdhjyrNkO3UM3Lilisxy-sdytdCqPl_2eic/edit?usp=sharing) in `FindVisitsByPatientUUIDListener` class was null, throwing a JSON Exception hence showing the wrong message. 
Added the basic checks for all the string values in JSON, whether they are in the JSON or not. Also the objects inside the JSON should not be null.

Fixed AC-131

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/fragments/FindPatientLastViewedFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/PatientArrayAdapter.java
openmrs-client/src/main/res/menu/download_multiple.xml
openmrs-client/src/main/res/values/strings.xml

This is version 1 of the feature proposed on [AC-160](https://issues.openmrs.org/browse/AC-160). I know many things are missing and I'll fix them in next version.
Screen-shots of progress is available on issue link.
Please review the Pull Request, and let me know  if any major change is needed. Or some other efficient way to do the same work.
Thanks

AC-160: Download mulitple patients data in one go, Version 1

---

openmrs-client/src/main/res/layout/activity_dashboard.xml
openmrs-client/src/main/res/values/strings.xml

For detailed description click below:
[Issue link](https://issues.openmrs.org/browse/AC-162)

AC-162: whole frameview for different actions should be clickable Fixed

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/FindPatientsSearchActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/fragments/FindPatientInDatabaseFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/fragments/FindPatientLastViewedFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/PatientArrayAdapter.java
openmrs-client/src/main/res/layout/fragment_find_patients.xml

[issue link](https://issues.openmrs.org/browse/AC-163)

AC-163: click event listeners should be work differently according to which fragment they are currently running

---

openmrs-client/src/main/java/org/openmrs/mobile/listeners/visit/CheckVisitBeforeStartListener.java

Corrected the argument being passed to the function `showStartVisitImpossibleDialog()`. This function should have patient name as argument.

Fixed AC-164

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/CaptureVitalsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/listeners/visit/FindVisitsByPatientUUIDListener.java
openmrs-client/src/main/res/values/strings.xml

Fixed AC-169: 'Checking Visits' Progress Dialog does not dismiss. Instead of showing a Toast, we should dismiss the progress dialog.

Fixed AC-169: 'Checking Visits' Progress Dialog does not dismiss

---

openmrs-client/src/main/java/org/openmrs/mobile/adapters/ActiveVisitsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/PatientHierarchyAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/PatientRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/PatientVisitsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/SettingsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/AnimationUtils.java

AC-170: Added Slide_in_left animation to Recycler View Items when they appear.

 AC-170: Added animation to Recycler View Items when they appear

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/LoginActivity.java

[issue-link](https://issues.openmrs.org/browse/AC-168)

AC-168:URL field gets cleared if user minimizes the app

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/LoginActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/fragments/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/URLValidator.java

Fixed AC-171: Trimmed the url at `getText()` and made sure uppercase letters are converted to lower case. `ensureProtocol()` function moved to `URLValidator` class.

Fixed AC-171

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/LoginActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/fragments/CustomFragmentDialog.java

Fixed AC-172: Added null checks and updated correct variable values on activity pause.

Fixed AC-172: 

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/RegisterPatientActivity.java
openmrs-client/src/main/res/layout/activity_register_patients.xml

@rkorytkowski I've added the changes you had mentioned.

AC 178: Implement Patient Registration Page - Adjustments added per JIRA comments

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/fragments/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/listeners/findPatients/FullPatientDataListener.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/PersonAddress.java
openmrs-client/src/main/java/org/openmrs/mobile/net/helpers/FindPatientsHelper.java

@rkorytkowski , I still could not emulate the error AC-189, I tried nearly 5 times. But I added a null check to the loader, just in case it might be the culprit. It did cause a force close once.

Fixed the loader in Patient Dashboard

---

openmrs-client/src/main/java/org/openmrs/mobile/api/PatientService.java
openmrs-client/src/main/java/org/openmrs/mobile/api/RestApi.java
openmrs-client/src/main/java/org/openmrs/mobile/api/RestServiceBuilder.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Location.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/IdentifierType.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/PatientIdentifier.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/Resource.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ResourceSerializer.java

@rkorytkowski @AvijitGhosh82 @tmarzeion 
please see issue [description](https://issues.openmrs.org/browse/AC-196)

AC-196 Create ResourceSerializer for custom Gson serializing

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/RegisterPatientActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/fragments/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/adapters/SimilarPatientsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/PatientService.java
openmrs-client/src/main/java/org/openmrs/mobile/api/RestApi.java
openmrs-client/src/main/java/org/openmrs/mobile/bundle/CustomDialogBundle.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/Results.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/PatientComparator.java
openmrs-client/src/main/res/layout/activity_register_patients.xml
openmrs-client/src/main/res/layout/fragment_dialog_layout.xml
openmrs-client/src/main/res/layout/openmrs_recycle_view.xml
openmrs-client/src/main/res/layout/similar_patient_row.xml
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/main/res/values/theme.xml

This PR contains commit from AC-196 PR because it requires those changes.  
I've some questions about the workflow:
1.In the current release when you register new user, you are redirect to the dashbord activity. Why not to the PatientDashbordActivity ? 
2. Why do we fetch patient in PatientDashbordActivity by uuid if we want to support offline mode? If we have more then one not synced patients we will always open the oldest one not synced. I quess this is a bug.

AC-195 show dialog with similar patients when registering new one

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

JDK upgrade is required for Travis

Update Gradle and JDK version

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/registerpatient/RegisterPatientActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/registerpatient/RegisterPatientContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/registerpatient/RegisterPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsPresenter.java
openmrs-client/src/main/res/layout/fragment_dashboard.xml

- removing any android libraries form presenters
- fixed crushing app when rotating the device
- fixed loading forms when changing server url in loginActivity

AC-204 fixes and clean up after applying mvp

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/diagnosis/PatientDiagnosisFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientVitalsFragment.java

The bug was also in vitals fragment so I fixed it too

AC-229 Delete Patient Button on Diagnosis tab doesn't have any effect

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java

I couldn't really hide patients from the adapter so I filter patients before passing them to the adapter. There is problem with deleting the whole row. I had to set heights, padding etc. of the row manually to look ok, but then I was getting some inconsistency errors when scrolling.

AC-235 Hide downloaded patients

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/listeners/forms/AvailableFormsListListener.java
openmrs-client/src/main/res/values/strings.xml

Minor grammatical and other edits to Strings.xml

Strings Edits

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/registerpatient/RegisterPatientActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardActivity.java
openmrs-client/src/main/res/menu/patient_details_menu.xml
openmrs-client/src/main/res/menu/patients_visit_tab_menu.xml

Added sync switch and 3 dots to all activities' menus

AC-232 - Top bar adjustments

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/values/strings.xml

- Initial Sync switch state is fixed
- Renamed Network to Sync
- Added Progressbar (on loading) and Snackbar (on error) when changing Server URL
- Removed loading splash screen on URL update
- Locked location dropdown when error occurs or server is loading

AC-231 - Login screen adjustments - Followup commit

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/res/drawable/ic_sync_off.xml
openmrs-client/src/main/res/drawable/ic_sync_on.xml
openmrs-client/src/main/res/layout/sync_switch.xml
openmrs-client/src/main/res/menu/basic_menu.xml

AC-232 - Top bar adjustments - Followup commit

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayMainPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPagePresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/EncounterService.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/Answer.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/Obscreate.java
openmrs-client/src/main/java/org/openmrs/mobile/models/retrofit/QuestionOptions.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/SelectOneField.java

AC-234 - Added support for coded field in forms

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardMainPresenterImpl.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDashboardDetailsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/diagnosis/PatientDashboardDiagnosisPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/diagnosis/PatientDiagnosisFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientDashboardVisitsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientVisitsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientDashboardVitalsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientVitalsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/res/values/strings.xml

Pull request according to AC-247
https://issues.openmrs.org/browse/AC-247
I added confirmation dialog to delete patients in patient details, diagnosis, visits and vitals views.

AC-247: App should ask for confirmation on deleting patient

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListPresenter.java
openmrs-client/src/main/res/layout/form_dropdown.xml

I've added missing encounter type error handling and improved layout look

AC-234 - Followup commit

---

openmrs-client/src/main/res/values/strings.xml

AC-261: Update Strings.xml
https://issues.openmrs.org/browse/AC-261
I removed unused strings. Fixed wrong strings and shortened too long title.

AC-261: Removed unused and fixed wrong strings in strings.xml file

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/test/unit/PatientBirthDateValidatorWatcherTest.java
openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardMainPresenterImpl.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientinfo/PatientInfoActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientinfo/PatientInfoContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientinfo/PatientInfoFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientinfo/PatientInfoPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientinfo/SimilarPatientsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/retrofit/PatientApi.java
openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/PatientBirthdateValidatorWatcher.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java
openmrs-client/src/main/res/drawable/ic_edit.xml
openmrs-client/src/main/res/layout/activity_patient_info.xml
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/menu/patient_details_menu.xml
openmrs-client/src/main/res/values/strings.xml

Added Update Patient functionality using the existing Register Patient Form. 
Also changed some fields of register patient to better help users fill in information. 
Renamed RegisterPatient to PatientInfo.

AC-258: Edit Patient Information

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDashboardDetailsPresenter.java
openmrs-client/src/main/res/menu/patient_details_menu.xml

@ykarim That wasn't very difficult :smile:

AC-288 - Name display is updated after editing patient

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayActivity.java

AC-272: Pages in forms are duplicated
https://issues.openmrs.org/browse/AC-272
I fixed duplication of pages in forms.

AC-272: Removed form pages duplication

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java

Added hideSoftKeys() to Login.

AC-273: The Keyboard on Login Screen

---

openmrs-client/src/main/res/layout/list_visit_group.xml
openmrs-client/src/main/res/values/dimens.xml

| BEFORE  | :sparkles: :sparkles: :sparkles: :sparkles: AFTER :sparkles: :sparkles: :sparkles: :sparkles:  |
| ------------- | ------------- |
| <img src="https://issues.openmrs.org/secure/attachment/48550/Screenshot_20170105-224046.png" width="250"/>  | <img src="https://issues.openmrs.org/secure/attachment/48555/FIXED.png" width="250"/>  |

AC-286 - Fixed Encounter Type icon display

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java

AC-263: Patient DOB goes back one day when synced with server
https://issues.openmrs.org/browse/AC-263
I fixed patient DOB bug

AC-263: Fixed patient DOB bug

---

README.md

Updated information and added screenshots.

AC-308: Update README on GitHub

---

openmrs-client/build.gradle

AC-322: Change Version Number of Latest Build

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientDashboardVisitsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/FilterUtil.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LastViewedPatientsPresenterTest.java

**TODO**:
:tada:  **DONE** :tada: 
________________________________
`*` - Won't fix, since extracting common code from adapter would make it less readable.

AC-316 - Remove code duplicates

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/StringUtils.java

I did it also for synced patient search

AC-319 fixed SearchView geting destroyed on orientation changed

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java

I have added TextView above each numeric field. See below

AC-331 Problem in editing patient's Vital Form

---

build.gradle
openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientDashboardVisitsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/EncounterService.java
openmrs-client/src/main/java/org/openmrs/mobile/api/retrofit/VisitApi.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/VisitDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/DBOpenHelper.java
openmrs-client/src/main/res/layout/fragment_active_visits.xml

@rkorytkowski @tmarzeion @lkukielka  @shivtej1505 @ykarim 
I would like you to take a look at this PR and give your thoughts. 
The main purpose of this is to make calls to the Sqlite in asynctasks. To achieve that I used RxJava, RxAndroid(for Schedulers) and Retrolamba(to make it look better :) ). I'm new to RxJava so if anyone of you knows it better please be sure to make proper review : ) 
I have to add this to saving and updating methods  still but wanted to show you what I have done so far to get some feedback faster :)

AC-293 using RxJava to get data from DB in asynctask - WIP

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayActivity.java

Along with adding the required feature I have also removed one unnecessary print statement.

AC-336 : Turn auto-lock off for forms

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/InputField.java

This is a fresh PR in reference to #307 . I closed the previous one as I messed up with the git while editing it. I have made the changes as suggested in #307.

AC-326 Text color is preserved during orientation change in Form Entry

---

openmrs-client/src/main/res/layout/fragment_dialog_layout.xml
openmrs-client/src/main/res/layout/fragment_matching_patients.xml
openmrs-client/src/main/res/layout/openmrs_edit_text_field.xml
openmrs-client/src/main/res/menu/basic_menu.xml

Not exactly sure what to do with the AppIndexing lint error.

AC-304: Lint adjustment - Usability

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayMainPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormPageAdapter.java

Moved the storage of form fragments to FormPageAdapter.

AC-334 : Numeric fields validation not working when orientation changed

---

openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/values/strings.xml

I've used [PermissionDispacher](http://hotchemi.github.io/PermissionsDispatcher/) library to avoid boilerplate code.

AC-366 handle camera&storage  permissions manually

---

openmrs-client/build.gradle
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/SettingsPresenterTest.java

@tmarzeion , as the `SettingsPresenter` uses static method `getInstance` from `OpenMRS` class, I had to use PowerMockito, if there is another way please let me know :)

AC-354: Unit test - SettingsPresenter

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/RestApi.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Results.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/res/layout/fragment_last_viewed_patients.xml
openmrs-client/src/main/res/layout/progressbar_item.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LastViewedPatientsPresenterTest.java

AC-343 Infinite Scroll functionality for Last Viewed Patients Activity

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/SimilarPatientsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/retrofit/PatientApi.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientDAO.java
openmrs-client/src/main/res/layout/fragment_form_entry_patient_list.xml
openmrs-client/src/main/res/layout/fragment_synced_patients.xml

I've implemented RxJava into 3 "bottleneck" places:
- Downloading multiple patients
- Form entry patient list
- Synced Patient list

AC-345 - Implemented RxJava in PatientDAO

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsRecyclerViewAdapter.java
openmrs-client/src/main/res/layout/activity_settings.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/SettingsPresenterTest.java

AC-376:Allow users to show log file in the app

---

openmrs-client/src/main/java/org/openmrs/mobile/databases/DBOpenHelper.java

From now on with this update we will have to always update the DB int the onUpgrade method when the dbversion version is changed. I did leave the comments how to do it.

AC-364 Handle DB updates

---

openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java

I didn't use `RxBinding` `filter` feature since I needed `else` logic here.

AC-374 - Added dynamic form fields validation

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/logs/LogsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/logs/LogsContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/logs/LogsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/logs/LogsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsRecyclerViewAdapter.java
openmrs-client/src/main/res/drawable/ic_copy.xml
openmrs-client/src/main/res/layout/activity_logs.xml
openmrs-client/src/main/res/layout/fragment_logs.xml
openmrs-client/src/main/res/values-w820dp/dimens.xml
openmrs-client/src/main/res/values/dimens.xml
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/SettingsPresenterTest.java

Now the logs are opened in a new activity with floating action button to copy all the logs.

Opens logs in a new activity

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java

JIRA issue link : https://issues.openmrs.org/browse/AC-392

AC-392:Download patient option not switching instantly

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java

Fix the [issue](https://issues.openmrs.org/browse/AC-393)

AC-393 logical error with patient photo

---

README.md

Added release notes for v2.6 and goals for v2.7 to README.md
Task link - https://issues.openmrs.org/browse/AC-371?filter=-3

AC-371: Update README.md

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java
openmrs-client/src/main/res/layout-land/list_visit_group.xml
openmrs-client/src/main/res/layout-large/list_visit_group.xml
openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/layout/key_value_data_row.xml
openmrs-client/src/main/res/layout/list_visit_group.xml
openmrs-client/src/main/res/values/states.xml

Partial fix for [AC-300 Lint Adjustment - Correctness](https://issues.openmrs.org/browse/AC-300).
SimpleDateFormat: Implied locale in date format >> Suppressed where confirmed to be custom implementation.
CommitPrefEdits: Missing commit() on SharedPreference editor >> Added apply().
ScrollViewSize: ScrollView size validation >> Replaced singleLine with maxLines where appropriate, removed altogether where unnecessary.

AC-300: Fixed some lint warnings

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsFragment.java

Fix [issue](https://issues.openmrs.org/browse/AC-397?jql=project%20%3D%20AC)

AC-397 Crash when close the internet in synced patients

---

build.gradle
openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardPagerAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientChartsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientDashboardChartsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/VitalsListAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Encounter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/DayAxisValueFormatter.java
openmrs-client/src/main/res/layout/fragment_patient_charts.xml
openmrs-client/src/main/res/layout/line_chart.xml
openmrs-client/src/main/res/layout/list_vital_group.xml
openmrs-client/src/main/res/values/strings.xml

I have added the charts to in the patient dashboard. Below are the screenshots.

AC-404:Vitals History Chart

---

openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/InputField.java
openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/layout/openmrs_edit_text_field.xml

I have added the TextInputLayout for the EditTexts. 
I have also replaced the EditText fields in the form with a SeekBar.

AC-406 : Minor Visual Improvements

---

openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java

It is a minor fix to change the default server URL.

Changes default server URL

---

openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.java
openmrs-client/src/main/res/values/color.xml
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/main/res/values/styles.xml

Adds app demo

---

README.md

**JIRA TICKET NAME:**
[AC-425 - Server URL dose't work with the provided developer credentials.](https://issues.openmrs.org/browse/AC-425)
**Summary:**
Previous server URL dose't work with the provided developer credentials.

 AC-425 - Server URL dose't work with the provided developer credentials.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
openmrs-client/build.gradle

I have added Kotlin to the build.gradle files. 
See https://issues.openmrs.org/browse/AC-436

[AC-436] Add Kotlin to build.gradle files

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/test/unit/DateUtilsTest.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java

https://issues.openmrs.org/browse/AC-439
Write a unit test for `validateDate` method at [DateUtils.java#149](https://github.com/openmrs/openmrs-contrib-android-client/blob/master/openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java#L149)

[AC-439] Write unit test for validateDate method

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientVitalsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/api/PatientService.java
openmrs-client/src/main/res/layout/fragment_patient_charts.xml
openmrs-client/src/main/res/layout/list_gallery_or_camera_item.xml
openmrs-client/src/main/res/values/strings.xml

https://issues.openmrs.org/browse/AC-441
Removed all hardcoded string from the xml and some activities (using String resources )

AC-441: Using @string resources instead of harcoded string

---

.travis.yml
appveyor.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
openmrs-client/build.gradle
openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/utilities/RangeEditText.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/URLValidator.java
openmrs-client/src/main/res/menu/find_locally_and_add_patients_menu.xml
openmrs-client/src/main/res/menu/find_patients_remote_menu.xml
openmrs-client/src/main/res/menu/find_visits_menu.xml
openmrs-client/src/main/res/menu/form_entry_patient_list_menu.xml

See https://issues.openmrs.org/browse/AC-437

[AC-437] Update dependencies and Gradle version

---

.travis.yml
appveyor.yml
build.gradle
openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/NotificationUtil.java

https://issues.openmrs.org/browse/AC-438
Upgrade compileSdkVersion and targetSdkVersion to the latest API level (27).

[AC-438] Upgrade to support latest Android Version

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml

Issue Link :https://issues.openmrs.org/projects/AC/issues/AC-430?filter=allopenissues

AC-430: Added a loading spinner when registering a new patient

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java

Resolved uncaught exception in showToast method in LoginFragment. 
https://issues.openmrs.org/browse/AC-449

[AC-449] Uncaught java.lang.NullPointerException in LoginFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ViewUtils.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/AddEditPatientPresenterTest.java

https://issues.openmrs.org/browse/AC-447
Added a function in `ViewUtils` to validate Strings to check for illegal characters in text fields. Also added tests to the presenter.
Screenshots of the UI are [name_errors](https://issues.openmrs.org/secure/attachment/51120/name_errors.png) and [invalid_address](https://issues.openmrs.org/secure/attachment/51119/address_error.png).

[AC-447] Add Data Validation when registering patients

---

openmrs-client/src/main/java/org/openmrs/mobile/utilities/ForceClose.java

Issue Link :https://issues.openmrs.org/projects/AC/issues/AC-444?filter=allopenissues 
I replaced  deprecated Build.version.SDK with Build.version.SDK_INT .

AC-444 : Replaced deprecated Build.version.SDK

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/VitalsListAdapter.java

JIRA issue Link https://issues.openmrs.org/browse/AC-453
please review : )

AC-453 :Fixed app crashes when the vitals list is opened

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java

I removed all the local reduntant variables  .Please have a look @Sub6Resources :). 
Issue Link : https://issues.openmrs.org/browse/AC-445

AC-445: Removed redundant variables

---

openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java

Issue Link : https://issues.openmrs.org/browse/AC-451 .

AC-451 :Fixed app crash on opening Form entry

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java

Issue Link: https://issues.openmrs.org/browse/AC-442

AC-442: Check for honeycomb or above is not necessary

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java

issue link: https://issues.openmrs.org/browse/AC-455
please review : )
I found some variable name such as: 
private View view;
Should I replace view with mView when fixing the issue?

AC-455:Fixed App crashes while showing toast.

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/drawable/btn_submit_bg_disabled.xml
openmrs-client/src/main/res/drawable/btn_submit_bg_normal.xml
openmrs-client/src/main/res/drawable/btn_submit_bg_pressed.xml
openmrs-client/src/main/res/drawable/btn_submit_selector.xml
openmrs-client/src/main/res/layout/activity_form_display.xml
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/values/color.xml

issue link: https://issues.openmrs.org/browse/AC-454

AC-454:Fixed progress bar does not show when registering patient

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/ChartsViewActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientChartsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientChartsListAdapter.java
openmrs-client/src/main/res/layout/activity_charts_view.xml
openmrs-client/src/main/res/layout/fragment_patient_charts.xml
openmrs-client/src/main/res/values/strings.xml

This is the Issue Link: https://issues.openmrs.org/browse/AC-463

AC-463:Improve Charts in Patient Dashboard

---

.travis.yml
appveyor.yml
build.gradle
openmrs-client/build.gradle
openmrs-client/src/main/AndroidManifest.xml

Issue at https://issues.openmrs.org/projects/AC/issues/AC-466

[AC-466] Update Android plugin for Gradle and other libraries

---

openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardPagerAdapter.java
openmrs-client/src/main/res/layout/activity_patient_dashboard.xml

Issue link: https://issues.openmrs.org/projects/AC/issues/AC-460

[AC-460] The TabHost component is not correctly displaying TabName in Patient Dashboard

---

build.gradle

I have fixed a build issue (which I reported before, in the link below).
This PR fixes a bug in gradle, which makes it impossible to import and build the project.
**All existing tests passed.**
https://issues.openmrs.org/browse/AC-481

AC-481: Fixed build.gradle file to fix build issues

---

openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.java

I've added checking value of session location Spinner on login page. If nothing is selected then login button is inactive.
https://issues.openmrs.org/browse/AC-429

AC-429: Can login without specifying location for systems that have login locations

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsPresenter.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ActiveVisitPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/AddEditPatientPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormEntryPatientListPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LastViewedPatientsPresenterTest.java

I've added some tests and edited existing ones to improve code coverage.
https://issues.openmrs.org/browse/GCI-286
https://codein.withgoogle.com/dashboard/task-instances/5511615827935232/

GCI-286: Improve Code Coverage for the Android client

---

README.md

Corrected few minor grammatical errors in this readme

Fix minor grammatical errors 

---

openmrs-client/src/test/java/org/openmrs/mobile/utilities/DateUtilsTest.java
openmrs-client/src/test/java/org/openmrs/mobile/utilities/TimeZoneRule.java

I have converted the `DateUtilsTest` as a unit test to make it faster to run because no Android components are needed. Also added a new rule so that the tests don't depend on the timezone.
JIRA Issue: https://issues.openmrs.org/browse/AC-513
​

AC-513: Move DateUtilsTest to a Unit test

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/PatientBirthdateValidatorWatcherTest.java
openmrs-client/src/test/java/org/openmrs/mobile/utilities/URLValidatorTest.java

Make the `URLValidatorTest` a unit test instead. Remove unused imports and import the `androidx` classes instead of `support`.
JIRA Issue: https://issues.openmrs.org/browse/AC-525

AC-525: Convert URLValidatorTest to a unit test

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/res/values/strings.xml

Imported Toast in ACBaseActivity.java and creating a toast whenever the syncbutton(the cloud icon on the toolbar) is tapped, notifying the user that he is connecting to/disconnecting from the server.  
Added 2 entires to strings.xml to avoid hard coding.
JIRA Issue: https://issues.openmrs.org/browse/AC-506
-  [x] My pull request only contains **ONE single commit**
-  [x] My pull request is **based on the latest changes** of the master branch.

AC 506 - Create toasts when toggling the syncbutton

---

openmrs-client/src/main/AndroidManifest.xml

Added provider tag and models in AndroidManifest.xml .
Adding provider tags fixed the SecurityException, but now classes extending Model like Link, FormResource, etc. weren't getting invoked, which was fixed by listing them out in AndroidManifest.xml .
JIRA Issue: https://issues.openmrs.org/browse/AC-487

AC-487: Client continuously force stop and restarts

---

openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java

Updated the convertTimeString() method of DateUtils.java class by checking for the length of the input and parsing it with suitable format to stop the app from crashing.
JIRA Issue: https://issues.openmrs.org/browse/AC-485

AC-485 Fixed crash when updating non-synchronized patient

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
openmrs-client/build.gradle
openmrs-client/src/main/res/values/styles.xml

Updated versions of required Components
JIRA Issue: https://issues.openmrs.org/browse/AC-519

AC-519 kotlin version error, causing build to fail

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java

The reason of the error was the snackbar was attached during fragment creation with indefinite length and was never dismissed. I changed the scope of snackbar to global and static so that it can referenced from within ACBaseActivity.java. Additionally I added another snackbar in ACBaseActivity.java to handle network connections from within the activity.
JIRA Issue: https://issues.openmrs.org/browse/AC-529

AC-529: 'No internet connect' when online

---

openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/ACUnitTestBase.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/SyncedPatientsPresenterTest.java

Made numbers to be an invalid character in name fields in the registration form of a new patient.
Changed the error message to be more helpful.
Fixed the alignment of the error box changed due to the changed error message.
The issue was unresolved because the test used the sample names as `given_name_1, middle_name_1` etc.
That caused the tests to fail.
The tests the sample names are changed to `given_name_a, middle_name_a`, etc. in this PR.
JIRA Issue: https://issues.openmrs.org/browse/AC-500

AC-500: Missing validation on patient's name during registration

---

build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/AddEditPatientPresenterTest.java

AC-532 Adding validation to fields of contact information 
In this commit I have added validation to contact information fields in the Register patient activity.
JIRA Issue: https://issues.openmrs.org/browse/AC-532

AC-532 Adding validation to fields of contact information 

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/res/layout/dialog_progress.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-462
- [] I have **added tests** to cover my changes. (If you refactored

AC-462 :improve__progress-dialog

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListFragment.java
openmrs-client/src/main/res/values/strings.xml

Instead of the solution proposed on the issue, I tried to fix this in the way similar to the web client.
All the patients are displayed in Form Activity but when a patient with inactive visit is clicked upon a snackbar is shown saying vitals can be captured for patients with active visists.
JIRA Issue: https://issues.openmrs.org/browse/AC-499

AC-499: Bad request in Form Entry

---

openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/layout/openmrs_edit_text_field.xml
openmrs-client/src/main/res/layout/openmrs_title_view_field.xml

Removed all the xml lint warnings described in the issue.
JIRA Issue: https://issues.openmrs.org/browse/AC-526

AC-526 Fix Lint Errors in XML files

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/DateUtils.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml

The error was caused to due to null reference of  ```restApi``` due to which empty response was generated during api calls. 
I fixed it by instantiating restApi properly.
Additionally, an if-else block was added in DateUtils.java to prevent app crash due to null pointer exception.
JIRA Issue: https://issues.openmrs.org/browse/AC-527

AC 527: Bad request when trying to start a visit

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java

Added ```android:configChanges="orientation|screenSize|keyboardHidden"``` so that the activity is not destroyed and created by itself when the device is rotated, preventing the unnecessary network calls on device rotation.
Added ```viewPager.setOffscreenPageLimit(adapter.getCount()-1);``` so that all the fragments are loaded at once and to prevent the recreation of fragment each time when switched between tabs.
JIRA Issue: https://issues.openmrs.org/browse/AC-541

AC-541: Handling multiple network calls

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml

Added Outlined Box style to edit texts
Migrated support library to androidX and material components as needed in the form , it was causing crash when opening the Register Patient button
Added Error messages as needed
Solved the issue of dialog box not showing when a user tries to abandon the activity while some of the data fields are filled.
JIRA Issue: https://issues.openmrs.org/browse/AC-539
- [x ] My pull request only contains **ONE single commit**
- [ x] My pull request is **based on the latest changes** of the master branch.

AC-539 Added Outlined Box in Patient Info Form

---

openmrs-client/src/main/java/org/openmrs/mobile/api/retrofit/PatientApi.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml
openmrs-client/src/main/res/values/strings.xml

Minor changes in xml file.
According to Wikipedia only alphanumeric postal code exist, so adding that line allows only alphanumeric postal codes.
JIRA Issue: https://issues.openmrs.org/browse/AC-489

AC-489: Non Alphanumeric Value in Postal Code Field

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
openmrs-client/src/main/java/org/openmrs/mobile/services/AuthenticateCheckService.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/res/values/strings.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-467

AC 467: user details change detection

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayPageFragment.java

The pull request contains changes to retrieve the values for vitals from saved instances on device rotation.
JIRA Issue: https://issues.openmrs.org/browse/AC-542

AC-542: Saving the vitals on screen rotation

---

openmrs-client/src/main/AndroidManifest.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-568

AC-568 : removed PHONE STATE and WIFI STATE permission

---

.travis.yml
build.gradle
openmrs-client/build.gradle

Remove generating coverage in CI, and the dependencies in `build.gradle`.
JIRA Issue: https://issues.openmrs.org/browse/AC-580

AC-580: Release 2.7.0

---

openmrs-client/build.gradle

A simple Clean & Build was required to do away with the errors.
Also updated the AndroidX version from Beta to Stable
JIRA Issue: https://issues.openmrs.org/browse/AC-581

AC-581: Failed to resolve variable ${project.groupId}

---

.travis.yml

Discussion is [here](https://talk.openmrs.org/t/auto-upload-apps-apk-and-its-details-to-play-store/22846). This renews the GitHub API key using the `travis setup releases` command.
JIRA Issue: https://issues.openmrs.org/browse/AC-584

AC-584: Renew GITHUB API key to deploy to Play store

---

.travis.yml
openmrs-client/build.gradle

Following this [Link](https://stackoverflow.com/a/50862140) Set the custom path to the release APK and made changes to Travis file for the location of APK.
JIRA Issue: https://issues.openmrs.org/browse/AC-585

AC-585 Set Custom Path for Release APK

---

openmrs-client/build.gradle

PR based on #543 
JIRA Issue: https://issues.openmrs.org/browse/AC-585

AC-585 Changed APK  location in build.gradle

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/res/values/strings.xml

I added a Toast message to inform user that he/she has successfully logged out.
JIRA Issue: https://issues.openmrs.org/browse/AC-569

AC-569: Added Toast after User Logout

---

openmrs-client/src/main/res/layout/fragment_patient_info.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-589

AC-589 added baselineAligned attribute

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java

Removed the static snack bar in `PatientDetailsFragment.java` and using the one in `ACBaseActivity.java`  by calling `showNoInternetConnectionSnackbar()`
JIRA Issue: https://issues.openmrs.org/browse/AC-588

AC-588 removed static snackbar

---

openmrs-client/src/main/res/layout/activity_form_display.xml
openmrs-client/src/main/res/layout/fragment_last_viewed_patients.xml
openmrs-client/src/main/res/layout/similar_patient_row.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-590

AC-590 Removed unused namespaces in xml files

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ToastUtil.java

Made a Variable to know whether App is in the foreground or not
JIRA Issue: https://issues.openmrs.org/browse/AC-586

AC-586 Show Toast when App is in Foreground

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitExpandableListAdapter.java

Visit note now visible (expanding) on clicking "Show Details" on a saved Visit Note.
JIRA Issue: https://issues.openmrs.org/browse/AC-554

AC-554: Visit Note not visible after clicking "Show Details" on a saved Visit Note

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/logs/LogsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/TabUtil.java

Removed Android SDK_INT Version check where version to be checked was less than 16 (11 in this case), as the Minimum SDK Version for this project is 16.
Also removed the function that checks if API level is greater than equal to 16, which it always would be.
JIRA Issue: https://issues.openmrs.org/browse/AC-587

AC587: Obsolete SDK_INT Version Check

---

.travis.yml
build.gradle
openmrs-client/build.gradle

Used the jacoco-android-gradle-plugin from https://github.com/arturdm/jacoco-android-gradle-plugin for test report and made changes in .travis.yml to upload the report to codecov.
JIRA Issue: https://issues.openmrs.org/browse/AC-483

AC-483 Added codecov to repository

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsRecyclerViewAdapter.java
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/SettingsPresenterTest.java

Added link to Privacy Policy to the Settings Page of the app.
JIRA Issue: https://issues.openmrs.org/browse/AC-579

AC-579: Added Privacy Policy link to Settings page

---

openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRSLogger.java

Added AsyncTask for saving log messages to the file. 
JIRA Issue: https://issues.openmrs.org/browse/AC-544
- [] I have **added tests** to cover my changes. (If you refactored

AC-544: Re-developing OpenMRSLogger

---

.travis.yml

JIRA Issue: https://issues.openmrs.org/browse/AC-594

AC-594 Travis CI Error  Added dist: trusty

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/ChartsViewActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/VitalsListAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/diagnosis/PatientDashboardDiagnosisPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitExpandableListAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/application/OpenMRS.java
openmrs-client/src/main/java/org/openmrs/mobile/bundle/FormFieldsWrapper.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/EncounterDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/LocationDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ObservationDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Encounter.java
openmrs-client/src/main/java/org/openmrs/mobile/models/EncounterType.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Form.java
openmrs-client/src/main/java/org/openmrs/mobile/models/FormResource.java
openmrs-client/src/main/java/org/openmrs/mobile/models/IdGenPatientIdentifiers.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Page.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Patient.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Person.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Question.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Resource.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Results.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Section.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/FontsUtil.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/SelectOneField.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ToastUtil.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormEntryPatientListPresenterTest.java

JIRA Issue: https://issues.openmrs.org/browse/AC-566

AC-566: Replace Explicit types with <>

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/res/values/strings.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-538

AC 538: Add Toast Message when going online.

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CameraOrGalleryPickerDialog.java
openmrs-client/src/main/res/drawable/ic_photo_delete.xml

Added an option to camera Dialog for Image Removal. As the Remove Photo option clicked change the Patientphoto to person_grey_icon Bitmap.
JIRA Issue: https://issues.openmrs.org/browse/AC-498

AC-498 Added Delete Image for Uploaded image

---

openmrs-client/build.gradle
openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ViewUtils.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml

Added country picker to register patient activity
JIRA Issue: https://issues.openmrs.org/browse/AC-555

Added country picker to Register patient activity

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsRecyclerViewAdapter.java

During the [PR](https://github.com/openmrs/openmrs-contrib-android-client/pull/552/files#r281136906) , some lines of code were deleted due to which Privacy Policy couldn't be viewed when clicked from the Settings tab.
Restore those line in this PR.
JIRA Issue: https://issues.openmrs.org/browse/AC-601

AC-601: Clicking on Privacy Policy in settings opens the Privacy Policy

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/bundle/CustomDialogBundle.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/res/drawable/card_grey.xml
openmrs-client/src/main/res/menu/delete_multi_patient_menu.xml
openmrs-client/src/main/res/values/color.xml
openmrs-client/src/main/res/values/strings.xml

Currently, in order to delete multiple patients, one needs to open each patient and delete each one individually, one at a time.
This process can be made much faster and easier for the user by adding a Contextual Action Bar to felicitate the process of deleting multiple patients at once.
JIRA Issue: https://issues.openmrs.org/browse/AC-557
(please click on the GIF for better viewing)

AC 557: Add Contextual Action Bar in Synced Patients to delete multiple patients at once.

---

openmrs-client/src/main/res/layout/fragment_patient_info.xml

Signed-off-by: Abdelaty<abdelaty.mohammedmagdi@gmail.com>
JIRA Issue: https://issues.openmrs.org/browse/AC-597

AC-597:Using left/right instead of start/end attributes.

---

openmrs-client/build.gradle

Added Kotlin dependency to the App level gradle file.
JIRA Issue: https://issues.openmrs.org/browse/AC-602

AC-602: Added Kotlin dependency to app level build.gradle file

---

README.md

Added release notes for new version and goals for next version (2.8)
JIRA Issue: https://issues.openmrs.org/browse/AC-603

AC-603: Release notes 2.7

---

.gitignore

Added **/openmrs-client/release** folder to gitignore.
JIRA Issue: https://issues.openmrs.org/browse/AC-605

AC-605: Add release folder to gitignore

---

openmrs-client/build.gradle

Upgraded Zetetic SQLCipher to latest version.
JIRA Issue: https://issues.openmrs.org/browse/AC-606

AC-606: Cannot Initailize SQLCipher

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Changed Gradle to 5.1.1
JIRA Issue: https://issues.openmrs.org/browse/AC-609

AC-609: Change Gradle to latest version

---

openmrs-client/build.gradle

JIRA Issue: https://issues.openmrs.org/browse/AC-612

AC-612: Release v2.7.2

---

openmrs-client/build.gradle

- Moved all plugins{} below buildscript{}
- Upgraded GPP
- Replaced jsonFile with ServiceAccountCredentials 
JIRA Issue: https://issues.openmrs.org/browse/AC-613

AC-613: Job 'generateReleasePlayResources' failed

---

.travis.yml
build.sh
load_files.sh
openmrs-client/build.gradle

Create separate scripts: 1 to load files on a tagged release, and another for building the project.
JIRA Issue: https://issues.openmrs.org/browse/AC-616

AC-616: Encrypt play store files earlier in CI build

---

openmrs-client/src/main/res/menu/find_locally_and_add_patients_menu.xml
openmrs-client/src/main/res/menu/find_patients_remote_menu.xml

Search is the primary function after opening Find Patients from Dashboard.
JIRA Issue: https://issues.openmrs.org/browse/AC-611

AC-611: Make Search primary function for Find Patients

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientChartsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/diagnosis/PatientDiagnosisFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientVisitsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientVitalsFragment.java
openmrs-client/src/main/res/drawable/ic_close_white_24dp.xml
openmrs-client/src/main/res/drawable/ic_delete_black_24dp.xml
openmrs-client/src/main/res/drawable/ic_edit_white_24dp.xml
openmrs-client/src/main/res/layout/activity_patient_dashboard.xml
openmrs-client/src/main/res/layout/custom_expandable_fab.xml
openmrs-client/src/main/res/layout/fragment_patient_details.xml
openmrs-client/src/main/res/menu/patient_details_menu.xml
openmrs-client/src/main/res/values/dimens.xml
openmrs-client/src/main/res/values/strings.xml

Added FAB to Coordinator Layout of activity_patient_dashboard.
JIRA Issue: https://issues.openmrs.org/browse/AC-621

AC-621:Add Floating Action Button in patient's Details tab

---

gradle/wrapper/gradle-wrapper.properties
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/SimilarPatientsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDashboardDetailsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientDashboardVisitsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientDashboardVitalsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/EncounterService.java
openmrs-client/src/main/java/org/openmrs/mobile/api/PatientService.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/LocationRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/RetrofitRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/VisitRepository.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/AddEditPatientPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LoginPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/MatchingPatientsPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardDetailsPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardVisitsPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardVitalsPresenterTest.java

Just refactoring. See the title.
Blocker for AC-400
https://github.com/openmrs/openmrs-contrib-android-client/pull/585
JIRA Issue: https://issues.openmrs.org/browse/AC-608

AC-608: rename data source to repositories

---

README.md
openmrs-client/build.gradle
openmrs-client/src/main/play/release-notes/en-US/default.txt

JIRA Issue: https://issues.openmrs.org/browse/AC-

Release 2.8.0

---

README.md

Updated Readme.md file.
JIRA Issue: https://issues.openmrs.org/browse/AC-629

Updated Readme.md files

---

README.md

Minor proposals on lines 97 & 98
JIRA Issue: https://issues.openmrs.org/browse/AC-77

Minor proposal on paragraph 77

---

openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Patient.java
openmrs-client/src/main/java/org/openmrs/mobile/models/PatientDto.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Person.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Resource.java
openmrs-client/src/test/java/org/openmrs/mobile/test/ACUnitTestBase.java

- Created constructor for Patient, Person and Resource classes
- Replaced setters with constructors of Patient and Person class
- Minor refactoring of code
JIRA Issue: https://issues.openmrs.org/browse/AC-617
(Refactored existing code, thus did not add any additional tests)
(I'm facing [this unresolved Bug](https://issues.openmrs.org/browse/AC-614) while running test cases on my machine, even on the unchanged master branch but since I only refactored the code I don't think we may need to test it much. Help from other contributers appreciated on this issue)

AC-617: Create Constructor for Patient model

---

openmrs-client/src/main/res/layout/activity_form_entry_patient_list.xml

Removed a redundant `LinearLayout` parent layout from the xml file.
https://issues.openmrs.org/browse/GCI-345

GCI-345 Removed redundant parent layout

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/res/values/strings.xml

In the CustomFragmentDialog, I updated the *Select Location* case to show the Toast message.
JIRA Issue: https://issues.openmrs.org/browse/AC-505

[AC-505] Show toast when location changes.

---

.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
README.md

Updated .gitignore and readme, and added a codestyle XML to .idea/codeStyles
JIRA Issue: https://issues.openmrs.org/browse/AC-639

[GCI-riskycase] AC-639: Set Code Style

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardActivity.java
openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/values/styles.xml

Replaced components in the LoginActivity with components from the material library to enhance the aesthetic appeal of the app and make the UI more elegant.
Fixed the splash screen issue that was occurring before. The issue was occurring because the loginFields were getting fetched by an API but the OpenMRS logo was already in the activity. Now, the OpenMRS logo appears after all the data has been fetched by the API which fixes the issue.
JIRA Issue: https://issues.openmrs.org/browse/AC-637

AC-637 Replace components with their material alternatives

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/services/AuthenticateCheckService.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ToastUtil.java

I have converted fields to local variables.
I have left all class variables as they were as they can be used in future use.
I have removed all variable which were not used in the files i.e they were assigned but never used.
JIRA Issue: https://issues.openmrs.org/browse/AC-600

AC-600 : Convert fields to local variables

---

openmrs-client/build.gradle
openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json

Resolved Schema Export Directory Warning. By referring to the below thread.
https://stackoverflow.com/questions/44322178/room-schema-export-directory-is-not-provided-to-the-annotation-processor-so-we/44424908#44424908 
JIRA Issue: https://issues.openmrs.org/browse/AC-647

AC-647: Schema Export Directory Warning

---

CONTRIBUTING.md

Drafted the Contribution Guidelines for the Android Client to help newcomers get started with contributing to the project.
JIRA Issue: https://issues.openmrs.org/browse/AC-649

AC-649: Create CONTRIBUTING.md

---

openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientDAO.java

PatientDAO crashes AC when inserting patient to db, so I added a check which mitigates the NullPointerException.
JIRA Issue: https://issues.openmrs.org/browse/AC-632

[AC-632] PatientDAO crashes AC when inserting patient to db

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormDisplayActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formdisplay/FormPageAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardPagerAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPagerAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/MatchingProviderRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/tables/ConceptTable.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/tables/EncounterTable.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/tables/LocationTable.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/tables/ObservationTable.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/tables/PatientTable.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/tables/VisitTable.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Resource.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Session.java
openmrs-client/src/main/java/org/openmrs/mobile/models/User.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/Model.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/content/ContentProvider.java

Annotated NotNull / Nullable where needed
JIRA Issue: https://issues.openmrs.org/browse/AC-564

AC-564 Annotated NotNull / Nullable where needed

---

openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/Cache.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/Configuration.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/Model.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/ModelInfo.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/TableInfo.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/content/ContentProvider.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/query/From.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/query/Set.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/util/ReflectionUtils.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/util/SQLiteUtils.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/util/SqlParser.java

Converted all occurrences of "Explicit types can be replaced with <>" and found a single instance of lambda function not being used so updated it too
JIRA Issue: https://issues.openmrs.org/browse/AC-566

AC-566 Explicit types can be replaced with <>

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/res/drawable-v21/ic_file_download_black_24dp.xml
openmrs-client/src/main/res/layout/activity_splash.xml
openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/layout/fragment_patient_details.xml

removed hardcoded strings and unused schema declaration
JIRA Issue: https://issues.openmrs.org/browse/AC-518

AC-518 Removed hardcoded strings

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/values/strings.xml

I have added an "about us" text view in login fragment and linked that text view to the OpenMRS android user guide.
Link -> https://openmrs.github.io/openmrs-android-client-user-guide/getting-started.html
JIRA Issue: https://issues.openmrs.org/browse/AC-652

AC-652 : Need for better Play Store listing for Android Client

---

build.gradle
openmrs-client/build.gradle
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/LocationRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/LocationRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabase.java

I created a DAO interface for LocationEntity
JIRA Issue: https://issues.openmrs.org/browse/AC-474

AC-474 Update LocationDao for room

---

openmrs-client/build.gradle
openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/Introduction/SplashActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardActivity.java
openmrs-client/src/main/res/layout/activity_dashboard.xml
openmrs-client/src/main/res/layout/activity_splash.xml
openmrs-client/src/main/res/values/styles.xml

I had to rectify following three bugs:
1. Firstly updated materials dependency to incoporate dayNight theme
2. Secondly, **updated and reverted** changed in PR #648 because of which, half of the activities lost their action bar and dark mode feature lost its functionality. :(
3. called setupTheme() in onResume of ACBaseActivity which is common for all activities 
JIRA Issue: https://issues.openmrs.org/browse/AC-648

AC-648 Dashboard now responds to change in app theme

---

openmrs-client/src/main/AndroidManifest.xml
openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/introduction/IntroActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/introduction/SplashActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/LanguageUtils.java
openmrs-client/src/main/res/layout/activity_splash.xml
openmrs-client/src/main/res/layout/fragment_settings.xml
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

I added a string resource file with all the strings translated in Hindi
JIRA Issue: https://issues.openmrs.org/browse/AC-515

AC-515 Added Language Translation for Hindi

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginPresenter.java
openmrs-client/src/main/res/layout/fragment_login.xml

1. I added the logo in scroll view
2.  removed the bug caused by merging of the previous PR where the openMRS logo was shown after fetching data and thus, after onResume, the logo was not visible as the function to show logo was not called in 5 cases
JIRA Issue: https://issues.openmrs.org/browse/AC-577

AC-577 OpenMrs image do not cuts off in landscape mode

---

README.md

…in the Development section of the file README.md
AC-653 Correcting the README.md file
I have changed the tab name from "other" to "Tabs and Indents" in the development section of file
JIRA Issue: https://issues.openmrs.org/browse/AC-653
- [ x] My pull request only contains **ONE single commit**
- [ x] All new and existing **tests passed**.
- [x ] My pull request is **based on the latest changes** of the master branch.

AC-653: README.md - replace 'other' to 'Tabs and Indents'

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/introduction/SplashActivity.java

In the splash screen the thread which was used was not destroyed when the splash screen was destroyed.
I used handlers and runnables instead of thread and destroyed the handlers callback in onDestroy method.
JIRA Issue: https://issues.openmrs.org/browse/AC-666

AC-666 : Cannot see Login page: LoginFragment is not attached to a Context

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/menu/submit_done_menu.xml
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

I've added a reset/clear icon in the AddEditPatientActivity, which resets:
- All the text fields
- Error Fields
- Error Icons
- Dates
- Patient Photo
- Added Hindi Translation
- Used icon provided in SDK
- Added Dialog to ask user for confirmation
Now we have an reset button in the toolbar
JIRA Issue: https://issues.openmrs.org/browse/AC-524

AC-524 Add Reset Button

---

README.md

I changed the old screenshots with the new one.
JIRA Issue: https://issues.openmrs.org/browse/AC-677

[AC-677]Changing screenshots in README.md

---

README.md

Fixed typo on line 88
JIRA Issue: https://issues.openmrs.org/browse/AC-

Fixed typo on line 88

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
openmrs-client/src/main/res/layout/activity_patient_dashboard.xml
openmrs-client/src/main/res/layout/activity_provider_dashboard.xml
openmrs-client/src/main/res/layout/fragment_patient_details.xml

1. Changed selectedTabColour in both dashboard activities
2. Updated layout of patient details fragment to make it interactive
JIRA Issue: https://issues.openmrs.org/browse/AC-680

AC-680 Made TabsVisible and Updated layout of patientDetailFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/res/layout/fragment_login.xml

I have rectified the password seeing option in the password edit text field
JIRA Issue: https://issues.openmrs.org/browse/AC-656

AC-656 : Rectify the Password seeing option

---

openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/PatientEntity.java

I have removed the Primary key conflict on PatientEntity. 
I have referred below mention thread for doing so  https://stackoverflow.com/questions/47868553/how-to-suppress-the-android-room-warning-primary-key-constraint-on-id-is-ignore
JIRA Issue: https://issues.openmrs.org/browse/AC-628

AC-628: Primary key conflict on PatientEntity

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardRecyclerViewAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ActiveAndroid/util/SQLiteUtils.java
openmrs-client/src/main/res/layout/activity_provider_dashboard.xml
openmrs-client/src/main/res/layout/row_find_last_viewed_patients.xml

use start/end attributes instead of left/right attributes, 
JIRA Issue: https://issues.openmrs.org/browse/AC-597

AC-597 Use start/end attributes instead of left/right attributes

---

openmrs-client/build.gradle
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/EncounterRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/EncounterRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabase.java

Updated EncounterDAO for room with six tests covered in it for all the functions
JIRA Issue: https://issues.openmrs.org/browse/AC-473

AC-473 Updated EncounterDAO for room

---

gradle.properties
openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.java

I have fixed the app crash which occured on entering the values in email and password textfields.
This happens because of accesssing the adapter which was empty thus producing null pointer exception. 
JIRA Issue: https://issues.openmrs.org/browse/AC-663

AC:663-Fixed app crash on entering values in email or password text fields

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml

added a calendar icon instead of a simple green button for the AddEditPatientFragment
JIRA Issue: https://issues.openmrs.org/projects/AC/issues/AC-682

AC-682 added a calendar Icon

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.java

I fixed the text alignment of the description of "Register Patient" and "Form Entry" in Showcase view.
JIRA Issue: https://issues.openmrs.org/browse/AC-712

AC-712 Fixed Text Alignment in ShowcaseView

---

openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientDAO.java

Just added check for patientID at PatientDAO and assigned it empty if it contained null value
[Reference](https://stackoverflow.com/questions/4572090/illegalargumentexception-the-bind-value-at-index-1-is-null)
JIRA Issue: https://issues.openmrs.org/browse/AC-727

AC-727 Fixed crash at Register Patient Activity

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java

There was crash due to referencing the parent activity after the activity was destroyed.
Added not null checks to prevent crashes.
JIRA Issue: https://issues.openmrs.org/browse/AC-723

AC - 723 Illegal State Exception - LoginFragment not attached to context

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java
openmrs-client/src/main/res/layout/fragment_active_visits.xml
openmrs-client/src/main/res/layout/fragment_form_entry_patient_list.xml
openmrs-client/src/main/res/layout/fragment_provider_management.xml
openmrs-client/src/main/res/layout/fragment_synced_patients.xml

I added swipe to refresh the layout feature in the following activities:
1. FindPatient
2. Find ActiveVisits
3. Find FormEntry
4. Find Providers
JIRA Issue: https://issues.openmrs.org/browse/AC-679

AC-679 Added SwipeToRefresh Feature in all the necessary Activities

---

openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json
openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/ConceptEntity.java

Concept Entity was empty i created the concept entity referring to the old sql code.
JIRA Issue: https://issues.openmrs.org/browse/AC-640

AC-640 Created Concept Entity

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitExpandableListAdapter.java
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

I added validations to make sure that the HIV status is shown to the user when viewing the Visit Notes if available.
JIRA Issue: https://issues.openmrs.org/browse/AC-684

AC-684 - Show 'yes' or 'no' instead of random characters in active visit details

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/res/layout/custom_expandable_fab.xml

1. used the co-ordinator layout for better handling of snackbars
2. overrode the ACBaseActivty function to pass in the desired FAB reference to the snackbar constructor
JIRA Issue: https://issues.openmrs.org/projects/AC/issues/AC-738

Fixed the Floating action button UI bug

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

Displayed Better confirmation message while resetting patient data
JIRA Issue: https://issues.openmrs.org/browse/AC-703

AC-703 Displayed Better confirmation messsage

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientVisitsFragment.java
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

Added a suitable message for the offline mode operation of android client upon starting Active Patient Visit in offline mode
JIRA Issue: https://issues.openmrs.org/browse/AC-728

AC-728 Should disable 'start visit' in offline mode

---

openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientChartsFragment.java
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

added 2 checks :
1. To check for the empty dataset
2. To check for the invalid dataset. Example Whether or not a person has HIV as "YES" cannot be displayed
JIRA Issue: https://issues.openmrs.org/browse/AC-713

AC-713 Added check before displaying charts

---

openmrs-client/src/main/res/layout/custom_expandable_fab.xml

I have removed the texts along the floating action buttons
JIRA Issue: https://issues.openmrs.org/browse/AC-704

AC-704 : Removed fab texts

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/ConceptRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ConceptRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabase.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/ConceptEntity.java

1. I removed the primary key variable from ConceptEntity as the primary key was already inherited from Resource.kt
2. Created ConceptDAO interface
3. Written tests to validate ConceptDAO working
!--- Describe your changes in detail -->
JIRA Issue: https://issues.openmrs.org/browse/AC-472

AC-472 Created ConceptDAO and covered necessary tests

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/test/ObservationRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ObservationRoomDAO.java

JIRA Issue: https://issues.openmrs.org/browse/AC-756

AC-756 Fixed ObservationRoomDAO Tests

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/PatientRoomDAOTest.java

1. Updated tests for asynchronous behavior
2. Created a render function to test all the fields of entity with minimal code
JIRA Issue: https://issues.openmrs.org/browse/AC-757

AC-757 Fixed PatientRoomDAO tests

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/LocationRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/LocationRoomDAO.java

JIRA Issue: https://issues.openmrs.org/browse/AC-755

AC-755 Fixed LocationRoomDAO tests

---

openmrs-client/build.gradle

Added missing testImplementation dependency
JIRA Issue: https://issues.openmrs.org/browse/AC-773

AC-773 updated the testImplementation dependencies

---

README.md

1. Updated Screenshot of Login Page
2. Updated the HTTP call debugging column with Chuck Library instead of Snooper Library.
3. Gave an external link to alternate servers
4. Under Objectives section, set version to 2.9+ and updated goals.
5. The User manual link was updated with a brand new manual
JIRA Issue: https://issues.openmrs.org/browse/AC-782

AC-782 Updated readme with latest version and added a new manual

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/res/layout/fragment_dialog_layout.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-779

AC-779 Updated UI of dialogue box

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardActivity.kt
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

1. added the toast messge using 1 sec time lag
2. added translations
3. reformatted code
JIRA Issue: https://issues.openmrs.org/browse/AC-

AC-731 added support for double back press for exiting the app

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardFragment.java
openmrs-client/src/main/res/layout/fragment_provider_management.xml

1. added coordinator layout and few changes to fix the UI bug
JIRA Issue: https://issues.openmrs.org/browse/AC-781

AC-781 fixed the FAB behind snackBar bug

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
openmrs-client/src/main/res/layout/fragment_add_provider.xml

Fixed the Fab behind the snackbar issue in addProvider
JIRA Issue: https://issues.openmrs.org/browse/AC-795

AC-795 fixed fab behind snackbar

---

build.gradle
openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/introduction/IntroActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/utilities/DayAxisValueFormatter.java
openmrs-client/versions.gradle

1. Updated dependency
2. Created a new file to store versions which is standard way. 
3. Few dependencies were repeated so removed them
4. Arranged the dependencies to represent a certain group
JIRA Issue: https://issues.openmrs.org/browse/AC-766

AC-766 Updated all the dependecies to latest versions

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardContract.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.java
openmrs-client/src/main/res/layout/activity_provider_dashboard.xml
openmrs-client/src/main/res/layout/custom_expandable_fab.xml

1. added an expandable FAB for the providerDashboard
2. removed the edit option 
3. made the contract class as interface 
4. refactored the expandableFAB layout ids to be generic and not specific to the patient
JIRA Issue: https://issues.openmrs.org/browse/AC-789

AC-789 Added expandable FAB for providerDashboard

---

openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardRecyclerViewAdapter.java
openmrs-client/src/main/res/layout/row_provider_management.xml
openmrs-client/versions.gradle

Removed Provider manager DashBoard swipe actions and the corresponding 3rd party library
JIRA Issue: https://issues.openmrs.org/browse/AC-789

AC-789 Removed swipe actions

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java

fixed the reverse flipping bug by removing static modifier on the flag variable
JIRA Issue: https://issues.openmrs.org/browse/AC-807

AC-807 fixed the reverse flipping bug

---

openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/PatientBirthdateValidatorWatcherTest.java
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/ConceptRoomDAOTest.java
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/EncounterRoomDAOTest.java
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/FormResourceRoomDAOTest.java
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/LocationRoomDAOTest.java
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/PatientRoomDAOTest.java
openmrs-client/src/androidTest/java/org/openmrs/mobile/test/ObservationRoomDAOTest.java
openmrs-client/src/androidTest/java/org/openmrs/mobile/test/VisitRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ConceptRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/EncounterRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/FormResourceDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/LocationRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ObservationRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/PatientRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/VisitRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabase.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/EncounterEntity.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/FormResourceEntity.kt
openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/PatientEntity.java
openmrs-client/src/main/java/org/openmrs/mobile/models/typeConverters/FormResourceConverter.java

1. Added formEntity to replace ActiveAndroid.
2. Looked through entire code to create queries in FormDAO interface
3. Updated Patient and Encounter Entities
4. Added new and updated previous tests depending on entity
JIRA Issue: https://issues.openmrs.org/browse/AC-817

AC-817 Create FormEntity and update other entity classes

---

openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/AllergyRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientDashboardAllergyPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/AllergyRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/AllergyRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabase.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/AppDatabaseHelper.java
openmrs-client/src/main/java/org/openmrs/mobile/databases/entities/AllergyEntity.kt
openmrs-client/src/main/java/org/openmrs/mobile/models/Allergy.kt
openmrs-client/src/main/java/org/openmrs/mobile/models/typeConverters/AllergyReactionConverter.java
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardAllergyPresenterTest.java

JIRA Issue: https://issues.openmrs.org/browse/AC-805

AC-805 Added offline support for Allergy Module

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
openmrs-client/src/main/res/drawable/admission_spinner.xml
openmrs-client/src/main/res/layout/fragment_form_admission.xml
openmrs-client/src/main/res/values/color.xml
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java

JIRA Issue: https://issues.openmrs.org/browse/AC-815

AC-815 Updated UI for admission form screen

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderDashboardPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderManagerDashboardPresenterTest.java

1. removed unnecessary restAPI param passing to the repository
2. fixed tests for the new changes.
JIRA Issue: https://issues.openmrs.org/browse/AC-827

AC-827 removed unnecessary restAPI param passing to the Provider repository

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardActivity.java
openmrs-client/src/main/res/layout/activity_provider_dashboard.xml
openmrs-client/src/main/res/values/color.xml

1. Removed collapsable toolbar
2. Added a new color which is similar to light black color in the dark mode
JIRA Issue: https://issues.openmrs.org/browse/AC-833

AC-833 Removed Collapsable bar in provider dashboard

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/DeleteProviderWorker.java
openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/UpdateProviderWorker.java
openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofitcallbacks/CustomApiCallback.java
openmrs-client/src/main/java/org/openmrs/mobile/listeners/retrofitcallbacks/CustomResponseCallback.kt

0. removed the usage of dummy callbacks from provider repository
1. migrated the callback to kotlin
2. added the missing licence
3. conformed to the callback interface and made relevant changes due to it
JIRA Issue: https://issues.openmrs.org/browse/AC-831

AC-831 removed the usage of dummy callbacks from provider repository

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java
openmrs-client/src/main/res/drawable/error_symbol.xml
openmrs-client/src/main/res/layout/fragment_add_provider.xml
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-836

AC-836 Improved UI for add provider screen

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsRecyclerViewAdapter.kt
openmrs-client/src/main/res/layout/row_find_visits.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-838

AC-838 Updated UI for active visits card view

---

openmrs-client/src/main/java/org/openmrs/mobile/utilities/PatientComparator.kt

1. Added required NPE checks for the comparator.
JIRA Issue: https://issues.openmrs.org/browse/AC-843

AC-843 Added possible NPE checks at PatientComparator

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/LoginValidatorWatcher.kt

made argument view nullable in onItemSelected listener
JIRA Issue: https://issues.openmrs.org/browse/AC-847

AC-847 Nullable view required in onItemSelected LoginValidatorWatcher

---

openmrs-client/src/main/res/drawable-hdpi/rectangle_shape_with_primary_text_color.xml
openmrs-client/src/main/res/layout/activity_patient_dashboard.xml
openmrs-client/src/main/res/layout/fragment_patient_details.xml
openmrs-client/src/main/res/values/attrs.xml
openmrs-client/src/main/res/values/styles.xml

When using attribute as a View's background, the app crashes failing to inflate the View
JIRA Issue: https://issues.openmrs.org/browse/AC-851

AC-851: Fix errors in inflating attr when using on View's background.

---

openmrs-client/src/main/AndroidManifest.xml

In this pull request I've fixed the problem of LoginActivity being removed from the stack as the "Unable to Login" is clicked.Now on clicking the backbutton in the Contact Us Activity, the last activity shows up i.e. LoginActivity. I've attached a video clip demonstrating the fix.
JIRA Issue: https://issues.openmrs.org/browse/AC-792

AC-792: Fix Login Activity back-stack

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/utilities/ApplicationConstants.kt

Added the Missing repository layer abstraction for 3 presenter methods.
JIRA Issue: https://issues.openmrs.org/browse/AC-842

AC-842 fixed the repository layer for AddEditPatient package

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/community/contact/ContactUsActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/logs/LogsActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/PatientDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardActivity.java

When we switch to Hindi language in the app, all texts were translated from English to Hindi but the title of the action bars was not translated to Hindi. They remained in English. Now on switching to Hindi Language, the title of action bars is also being translated to Hindi.
JIRA Issue: https://issues.openmrs.org/browse/AC-866

AC-866 Title of action bars translated to Hindi also.

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providerdashboard/ProviderDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java

Refactored Provider Repository to extend the common Abstract Class and removed app context dependency from UI layer.
JIRA Issue: https://issues.openmrs.org/browse/AC-872

AC-872 Provider Repository refactoring

---

openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

AC-868: Address Edittext hint should mention "Address Line" instead of "Address"
In the Register Patient Activity, in the Edittext field of Address there should be a hint like "Address Line 1", "Address Line 2" instead of only "Address".
Before: Address 1, Address 2
Now: Address Line 1, Address Line 2
JIRA Issue: https://issues.openmrs.org/browse/AC-868
- No new tests required.
**Old**
**New**

AC-868: Updated Address EditText fields

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt

I have replaced `findViewById` calls by _**ViewBinding**_ in Dashboard fragment to ensure compile time safety.
JIRA Issue: https://issues.openmrs.org/browse/AC-870

AC-870: Use of Viewbinding instead of findViewbyId calls in Dashboard fragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.kt
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/BaseRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormAdmissionPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderDashboardPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/ProviderManagerDashboardPresenterTest.java

1. refactored Tests related to the changes and used the parents members instead of instanciating a new variable.
JIRA Issue: https://issues.openmrs.org/browse/AC-874

AC-874 Restructured provider and patient repositories

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardPresenter.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/LocationRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/VisitRepository.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LoginPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardDetailsPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardVisitsPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/PatientDashboardVitalsPresenterTest.java

Refactored repository and tests to extend base repository.
JIRA Issue: https://issues.openmrs.org/browse/AC-881

AC-881 Refactored Visit and location repository

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardActivity.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-884

Reallocated MVP to Dashboard

---

openmrs-client/src/main/java/org/openmrs/mobile/api/repository/PatientRepository.java

1. Reverted to patientIdentifierService class, Issue discussed here https://github.com/openmrs/openmrs-contrib-android-client/pull/847/files#r583491024
JIRA Issue: https://issues.openmrs.org/browse/AC-833

AC-833 NPE fixed at PatientRepository due to patientIdentifierService Omission

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardFragment.java

1. Used view Binding in both Activity as well as Fragment.
JIRA Issue: https://issues.openmrs.org/browse/AC-886

AC-886 using viewBinding for ProviderManagerDashboard package

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml

Navigation Component is now available in the app, so used 'compile-time-safe' activity transactions methods for the Dashboard
JIRA Issue: https://issues.openmrs.org/browse/AC-875

AC-875: Added Navgraph directions for dashboard buttons

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/activevisits/ActiveVisitsFragment.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-896

AC-896: Memory leak fixed in ActiveVisitsFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java

I replaced syncedPatientsActivity.finish() with syncedPatientsActivity.recreate() so that after deleting the patient(s), the app would not return to the home screen but rather remove the deleted patients from the list and remain on the SyncedPatientsActivity which will enhance the user experience.
JIRA Issue: https://issues.openmrs.org/browse/AC-962

AC-962 Made the application stay on SyncedPatientsActivity after deleting patients

---

README.md

Screenshots in GitHub README file look compressed in height. So, we can add some more height to it. Images' device's aspect ratio is about 1.87 height to width, multiplying this to our width modified in README file (280) = about 520 height; which would look better.
Changed height of each screenshot to 520px.
JIRA Issue: https://issues.openmrs.org/browse/AC-958

AC-958 : Correcting app screenshots' aspect ratio in README.md file

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formlist/FormListFragment.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-902

AC-902: Resolved memory leaks in FormListFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditallergy/AddEditAllergyFragment.java

Just nullified the binding.
JIRA Issue: https://issues.openmrs.org/browse/AC-899

AC-899: Fixed Memory Leak for AddEditAllergyFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt
openmrs-client/src/main/res/navigation/dashboard_nav_graph.xml

Changed ProviderDashboardActivity to ProviderManagerDashboardActivity in Nav Graph.
Reference - Comments in this PR  https://github.com/openmrs/openmrs-contrib-android-client/pull/852
JIRA Issue: https://issues.openmrs.org/browse/AC-929

AC-929 Changed ProviderDashboardActivity to ProviderManagerDashboardActivity in Nav Graph

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dashboard/DashboardFragment.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-901

AC-901: Resolved memory leaks in DashboardFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formentrypatientlist/FormEntryPatientListFragment.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-904

AC-904: Resolved memory leaks in FormEntryPatientListFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java

JIRA Issue: https://issues.openmrs.org/browse/AC-900

AC-900: Resolved memory leaks in AddEditPatientFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionFragment.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-905

AC-905: Resolved memory leaks in FormAdmissionFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java

JIRA Issue: https://issues.openmrs.org/browse/AC-903

AC-903: Resolved memory leaks in LoginFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/logs/LogsFragment.kt

Nullified the binding and created requisite changes to make _binding nullable.
JIRA Issue: https://issues.openmrs.org/browse/AC-913

AC-913: Fixed Memory Leak in Logs Fragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientPhotoActivity.java

Using ViewBinding for PatientDetailsFragment. with subtle changes in a function to make full use of viewBinding.
JIRA Issue: https://issues.openmrs.org/browse/AC-917

AC-917 Using ViewBinding for PatientDetailsFragment

---

openmrs-client/src/main/res/layout/fragment_settings.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-890

AC-890: Made improvement in the language change spinner.

---

openmrs-client/src/main/res/layout/fragment_add_provider.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-976

AC-976:Made the text in the text boxes displayed correctly in dark mode

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/visits/PatientVisitsFragment.java

1. Using View binding for PatientVisits Fragment.
2. taking care of leaks.
JIRA Issue: https://issues.openmrs.org/browse/AC-919

AC-919 : Using View Binding in PatientVisitsFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/diagnosis/PatientDiagnosisFragment.java

1. Using View Binding for fragment.
2. taking care of leaks.
JIRA Issue: https://issues.openmrs.org/browse/AC-918

AC-918: using view binding in patientDiagnosis package

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/matchingpatients/MatchingPatientsFragment.java

1. Used viewBinding in activity as well as fragment in the matching patient package.
2. made the binding instance local in activity to escape overring `onDestroyView()` function.
JIRA Issue: https://issues.openmrs.org/browse/AC-914

AC-914 :  Used ViewBinding in Matching Patients package

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/vitals/PatientVitalsFragment.java

1. used view Binding for all the resource elements.
2. taken care of resource leaks.
3. removed old hungarian notation from variable names.
JIRA Issue: https://issues.openmrs.org/browse/AC-920

AC-920 : used viewBinding for Patient vitals package

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/lastviewedpatients/LastViewedPatientsFragment.java

1. added binding for fragment and activity as well.
2. taken care of onDestroy on fragment.
JIRA Issue: https://issues.openmrs.org/browse/AC-912

AC-912 : used ViewBinding for lastViewed patients package

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/visitdashboard/VisitDashboardFragment.java

1. left the nullifying of binding in activity since its a local variable.
2. Used ViewBinding for whole package.
JIRA Issue: https://issues.openmrs.org/browse/AC-925

AC-925 : Used Viewbinding for VisitDashboard package.

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/syncedpatients/SyncedPatientsFragment.java

1. Used ViewBinding in SyncedPatients package.
JIRA Issue: https://issues.openmrs.org/browse/AC-924

AC-924 : Used ViewBinding in SyncedPatients package.

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/charts/PatientChartsFragment.java

1. Added required Override.
JIRA Issue: https://issues.openmrs.org/browse/AC-916

AC-916 : Fixed Memory Leak in PatientChartsFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/addprovider/AddProviderFragment.java

1. Added required override.
JIRA Issue: https://issues.openmrs.org/browse/AC-922

AC-922 : Resolved Memory Leak in AddProviderFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/allergy/PatientAllergyFragment.java

1. Added missing overriden function for cleaning up the binding.
JIRA Issue: https://issues.openmrs.org/browse/AC-915

AC-915 : resolved memory leak in PatientAllergyFragment

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/providermanagerdashboard/ProviderManagerDashboardFragment.java

1. After going through debugger and logs it seems we need this callBack for now since the delete operation doesnt return any flag like edit and create so we cant react accordingly.
JIRA Issue: https://issues.openmrs.org/browse/AC-983

AC-983 : Fixed DataSet Update bug in the Provider Dashboard

---

openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ProviderRoomDAO.java

1. Incase device is offline we shouldnt display null rather than we should display what is there in the database with a log that offline sync failed.
2. while inserting the server data in our offline db we must not replace rather ignore if conflicts occur since it might have been updated offine and it will get updated to the server through the worker in a while.
JIRA Issue: https://issues.openmrs.org/browse/AC-864

AC-864 : Made some changes in workflow

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsFragment.kt

1. Added required override and made necessary changes.
JIRA Issue: https://issues.openmrs.org/browse/AC-923

AC-923 : Resolved Memory Leaks in Settings Fragment

---

openmrs-client/build.gradle
openmrs-client/src/main/java/org/openmrs/mobile/api/RestServiceBuilder.java
openmrs-client/versions.gradle

Updated the older version of the chucker library with the newer version. This resolved NPE in Register Patient Activity.
JIRA Issue: https://issues.openmrs.org/browse/AC-967

AC-967 Resolved NPE in Register Patient Activity

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientPhotoActivity.java

1. added null checks for photo field which was causing NPE as seen in logs but not always hence better to use precautionary checks.
JIRA Issue: https://issues.openmrs.org/browse/AC-982

AC-982 : NPE in PatientPhotoActivity

---

openmrs-client/src/main/java/org/openmrs/mobile/api/workers/allergy/DeleteAllergyWorker.java

1. for updation and addition we cant have offline support since they need to fetch concepts on the fly to create or update allergies.
2. for deletion we can have offline support using workers since no such requirement exists.
JIRA Issue: https://issues.openmrs.org/browse/AC-984

AC-984 : Delete Operation Offline Support for Allergy Respository.

---

openmrs-client/schemas/org.openmrs.mobile.databases.AppDatabase/1.json
openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/ProviderRoomDAOTest.java
openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/AddProviderWorker.java
openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/DeleteProviderWorker.java
openmrs-client/src/main/java/org/openmrs/mobile/api/workers/provider/UpdateProviderWorker.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ProviderRoomDAO.java
openmrs-client/src/main/java/org/openmrs/mobile/models/Provider.kt

First, these 3 issues are related to each other and the same classes (and lines of code) need to be changed, so I've combined them in one PR for not producing merge conflicts.
1. Fixed provider's name being _[givenName givenName]_ instead of _[givenName familyName]_ in server when reconnecting to the internet. [AC-968]
2. Fixed AddProviderWorker being called forever even after success. [AC-969]
3. Fixed failing to edit or delete a newly created Provider in both online and offline modes. [AC-970]
JIRA Issue:
https://issues.openmrs.org/browse/AC-968
https://issues.openmrs.org/browse/AC-969
https://issues.openmrs.org/browse/AC-970

AC-968/AC-969/AC-970: Fix Provider module offline support issues

---

openmrs-client/src/main/java/org/openmrs/mobile/api/repository/ProviderRepository.java
openmrs-client/src/main/java/org/openmrs/mobile/dao/ProviderRoomDAO.java

1. used all the data structures I have learnt to convert this operation from O(N^2) to O(N) but with extra O(N) auxiliary space
2. taken care of offline entities as well.
JIRA Issue: https://issues.openmrs.org/browse/AC-896

AC-986 : Fixed up redundant provider insertions in local db

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LocationArrayAdapter.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.java
openmrs-client/src/main/res/layout/fragment_login.xml
openmrs-client/src/main/res/layout/spinner_item.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-889

Ac 889: Made improvements in the login page to correct many things not visible correctly in dark mode.

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/settings/SettingsPresenter.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-946

AC-946: Solved the bug in language switching feature.

---

openmrs-client/src/main/res/layout/row_find_synced_patients.xml

JIRA Issue: https://issues.openmrs.org/browse/AC-972
| Before | After |
| ------- | ------ |
| <img src="https://user-images.githubusercontent.com/65807152/133210760-09bba7f8-ceb7-4695-80d1-82b1e9343566.jpg" width=250> | <img src="https://user-images.githubusercontent.com/65807152/133210571-ae46298a-71a9-49b9-a412-b01794934755.jpg" width=250> |

AC-972: SyncedPatient TextView overlaps with ImageView

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java

The app was not working fine in Dark Mode, bugs that I found was (Adding Patient, Making Patient Visit)
https://user-images.githubusercontent.com/65807152/134677724-164fa7a2-f695-4614-918d-e7c2e8ab167c.mp4
https://user-images.githubusercontent.com/65807152/134678061-e275f1c5-7a77-4aea-a2d6-480e63c466e8.mp4
JIRA Issue: https://issues.openmrs.org/browse/AC-987

AC-987: PatientDetailFragment Binding Error

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/formadmission/FormAdmissionPresenter.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-990
https://user-images.githubusercontent.com/65807152/136155047-41ee3465-d957-46ad-9b45-b1f3040052de.mp4
https://user-images.githubusercontent.com/65807152/136155059-e034cbb4-626f-4944-a93b-552d23680f2a.mp4

AC-990: FormAdmissionFragment Binding

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.java
openmrs-client/src/main/res/layout/fragment_patient_info.xml

In Patient Registration, add backslash in DOB editText dynamically and  add 0 before date & month while selecting date from datepicker to maintain date format.
JIRA Issue: https://issues.openmrs.org/browse/AC-988
https://issues.openmrs.org/secure/attachment/60106/Screenshot_20210331-175757_OpenMRS_Android_Client%5B1%5D.jpg
https://user-images.githubusercontent.com/75332758/139407879-8207b13f-4c39-417e-9352-aa59c9e903df.mp4

AC-988 : Add backslash in AddEditPatient

---

openmrs-client/src/main/res/layout/fragment_add_provider.xml

Add scrollview as root layout in fragment_add_provider
https://user-images.githubusercontent.com/65807152/150650359-0e92b7ae-6f87-4f04-82a5-10c7f9727b24.mp4
JIRA Issue: https://issues.openmrs.org/browse/AC-1011

AC-1011 FragmentAddProvider not scrollable

---

openmrs-client/src/main/res/layout/fragment_form_admission.xml

Add Scrollview as root view in fragment_form_admission
https://user-images.githubusercontent.com/65807152/150629351-5504a46b-5469-4680-a8c6-a46108d7a376.mp4
JIRA Issue: https://issues.openmrs.org/browse/AC-1012

AC-1012: FragmentFormAdmission not scrollable

---

openmrs-client/src/test/java/org/openmrs/mobile/utilities/DayAxisValueFormatterTest.kt

Added tests for DayAxisValueFormatter class
JIRA Issue: https://issues.openmrs.org/browse/AC-1021

AC-1021 : Add test for DayAxisValueFormatter

---

openmrs-client/src/test/java/org/openmrs/mobile/utilities/PatientComparatorTest.kt

Tests added for Patient Comparator and passed successfully
JIRA Issue: https://issues.openmrs.org/browse/AC-1019

AC-1019: Patient-Comparator-Test

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/dialog/CustomFragmentDialog.java
openmrs-client/src/main/res/layout/fragment_dialog_layout.xml
openmrs-client/src/main/res/layout/openmrs_text_view_field.xml
openmrs-client/src/main/res/layout/row_single_checked_layout.xml
openmrs-client/src/main/res/values-night/theme.xml
openmrs-client/src/main/res/values/theme.xml

AC-992 : Improved Dark Mode
In Dark mode, theme of custom dialog is light which is straining to eyes in dark.
I Changed it to dark theme.
JIRA Issue: https://issues.openmrs.org/browse/AC-992
https://drive.google.com/file/d/183Wy5PNdKAqUI5Titx3w2LAtunwWMfNf/view?usp=sharing

AC-992: Improved Dark Mode

---

build.gradle
openmrs-android-sdk/build.gradle
openmrs-client/build.gradle
openmrs-client/versions.gradle

Added Hilt & JUnit 5 dependencies. Also, removed JUnit 4 duplicate dependency in androidTestImplementation as it is already added in testImplementation.
JIRA Issue: https://issues.openmrs.org/browse/AC-1028

AC-1028: Add Hilt & JUnit 5 dependencies & remove JUnit 4 duplicate dependency

---

openmrs-client/build.gradle
openmrs-client/src/test/java/org/openmrs/mobile/test/ACUnitTestBase.java
openmrs-client/src/test/java/org/openmrs/mobile/test/ResourceSerializerTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/FormDisplayPagePresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/test/presenters/LoginPresenterTest.java
openmrs-client/src/test/java/org/openmrs/mobile/utilities/DateUtilsTest.java

- Added Mockito Kotlin library dependency to test Kotlin classes with non-null mocks.
- Modified the unresolved references resulting from that.
JIRA Issue: https://issues.openmrs.org/browse/AC-1044

AC-1044: Add Mockito-Kotlin dependencies to the project

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AllergyRepository.java
openmrs-client/src/main/res/layout/fragment_patient_allergy.xml
openmrs-client/src/main/res/values-hi/strings.xml
openmrs-client/src/main/res/values/strings.xml

Fixed patient sync error that occurs in patient dashboard screen due to allergy sync error.
JIRA Issue: https://issues.openmrs.org/browse/AC-1051

AC-1051: Fix patient dashboard sync error due to allergy sync error

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/FormResourceRoomDAOTest.java

Fixed failing tests of FormResourceRoomDAOTest.
JIRA Issue: https://issues.openmrs.org/browse/AC-1054

AC-1054: Fix failing tests of FormResourceRoomDAOTest

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/dao/ProviderRoomDAOTest.java

Fixed failing tests of ProviderRoomDAOTest.
JIRA Issue: https://issues.openmrs.org/browse/AC-1055

AC-1055: Fix failing tests of ProviderRoomDAOTest

---

openmrs-client/src/androidTest/java/org/openmrs/mobile/listeners/watcher/PatientBirthdateValidatorWatcherTest.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/addeditpatient/AddEditPatientFragment.kt
openmrs-client/src/main/java/org/openmrs/mobile/listeners/watcher/PatientBirthdateValidatorWatcher.kt

Fixed failing tests of PatientBirthdateValidatorWatcherTest.
JIRA Issue: https://issues.openmrs.org/browse/AC-1056

AC-1056: Fix failing tests of PatientBirthdateValidatorWatcherTest

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/LocationDAO.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabase.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/ACBaseActivity.java
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginFragment.kt
openmrs-client/src/main/java/org/openmrs/mobile/activities/login/LoginViewModel.kt
openmrs-client/src/main/java/org/openmrs/mobile/services/AuthenticateCheckService.java
openmrs-client/src/main/java/org/openmrs/mobile/services/FormListService.java
openmrs-client/src/test/java/org/openmrs/mobile/test/viewmodels/LoginViewModelTest.kt

Fixed app crash that happens after login two consecutive times.
JIRA Issue: https://issues.openmrs.org/browse/AC-1057

AC 1057: Fix app crash after login two consecutive times

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/LoginRepository.kt

Fixed Login crash by retrieving sessionId from header
JIRA Issue: https://issues.openmrs.org/browse/AC-1068

AC-1068: Fix Login crash by sessionId 

---

.github/android.yml

- Earlier AppVeyor used to build and verify new PRs but apparently It's not working on the present PRs
- Added yml file for GitHub for the incoming PRs
JIRA Issue: https://issues.openmrs.org/browse/AC-1075

AC-1075: Revive GitHub CI Integration

---

openmrs-client/src/main/java/org/openmrs/mobile/activities/patientdashboard/details/PatientDetailsFragment.kt

- Details fragment title of patient id shows null when viewing patient details. 
- Fixed this with a condition check for the identifier
JIRA Issue: https://issues.openmrs.org/browse/AC-

AC-1070: Offline Patient Identifier fix

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/RestApi.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/EncounterRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/VisitRepository.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/EncounterDAO.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/EncounterRoomDAO.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabase.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/entities/EncounterEntity.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/entities/StandaloneEncounterEntity.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/EncounterType.kt

- New APIs for Encounters like fetching and saving Encounter Resources
- Created functions for Encounter DAO for saving and deleting records
- Changed schema of entities
- Created new entities
JIRA Issue: https://issues.openmrs.org/browse/AC-1072

AC-1072: Add APIs for Encounter functions to the SDK

---

openmrs-client/src/main/res/layout/fragment_patient_details.xml

Changed the constraints and width of text view of patient detail screen
https://issues.openmrs.org/browse/AC-1066

AC-1066 Patient Details screen do not show long names properly

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/RestApi.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/EncounterRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ObservationRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/EncounterDAO.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/EncounterRoomDAO.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/ObservationDAO.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/ObservationRoomDAO.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabase.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/entities/ObservationEntity.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/entities/StandaloneObservationEntity.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/ConceptClass.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/Observation.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/utilities/ObservationDeserializer.kt

- This PR is for the enhancement of the Observation APIs in the SDK
JIRA Issue: https://issues.openmrs.org/browse/AC-1077

AC-1077: Add/Enhance Observation APIs

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/RestApi.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/VisitRepository.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/VisitRoomDAO.kt

JIRA Issue: https://issues.openmrs.org/browse/AC-1079

AC-1079: Add/Enhance Visit APIs in SDK

---

openmrs-android-sdk/build.gradle
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/BaseRepository.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/di/modules/FakeAppDatabaseModule.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/di/modules/FakeApplicationContextModule.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/di/modules/FakeOpenMRSLoggerModule.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/di/modules/FakeRestServiceModule.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/di/modules/FakeWorkManagerModule.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/di/modules/SpyAppointmentRepositoryModule.kt

Necessary changes for Unit testing
JIRA Issue: https://issues.openmrs.org/browse/AC-1089

AC-1089: Changes for unit testing

---

openmrs-android-sdk/build.gradle
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/BaseRepository.kt

Necessary changes for Unit Testing
JIRA Issue: https://issues.openmrs.org/browse/AC-1089

AC-1089: Add changes for Unit testing

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/RestApi.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/OrderRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/OrderRoomDAO.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabase.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/entities/OrderEntity.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/OrderCreate.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/OrderGet.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/OrderResouce.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/OrderResource.kt
openmrs-android-sdk/src/main/res/values/strings.xml

- This is the start of the new feature for the SDK.
- This feature enables the implementers to interact with the "Orders" endpoint of the OpenMRS through the SDK
JIRA Issue: https://issues.openmrs.org/browse/AC-1082

AC:1082: Orders Feature for SDK

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/RestApi.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/di/modules/AppDatabaseModule.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/VisitType.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/AppointmentRepositoryTest.kt
openmrs-android-sdk/src/test/resources/mocked_responses/AppointmentRepository/AppointmentBlockCreate-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/AppointmentRepository/AppointmentCreate-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/AppointmentRepository/TimeSlotCreate-success.json
openmrs-client/src/test/java/org/openmrs/mobile/test/ACUnitTestBase.java
openmrs-client/src/test/java/org/openmrs/mobile/test/viewmodels/LoginViewModelTest.kt

Added Unit tests for the Appointment Repository
JIRA Issue: https://issues.openmrs.org/browse/AC-1088

AC-1088: Add Tests for Appointment Repository (Rebased)

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/RestApi.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/VisitRepository.java
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/VisitRepositoryTest.kt
openmrs-android-sdk/src/test/resources/mocked_responses/VisitRepository/GetVisit.json
openmrs-android-sdk/src/test/resources/mocked_responses/VisitRepository/GetVisitType.json
openmrs-android-sdk/src/test/resources/mocked_responses/VisitRepository/VisitsGet-success.json

- Added unit tests for VisitRepository
JIRA Issue: https://issues.openmrs.org/browse/AC-1090

AC-1090: Add Tests for Visit Repository

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/RestApi.java
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/EncounterRepository.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/EncounterRepositoryTest.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/di/modules/FakeAppDatabaseModule.kt
openmrs-android-sdk/src/test/resources/mocked_responses/EncounterRepository/EncounterGet-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/EncounterRepository/EncounterPost-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/EncounterRepository/EncounterResourcesGet-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/EncounterRepository/VisitGet-success.json

- Added Unit tests for EncounterRepository.kt
JIRA Issue: https://issues.openmrs.org/browse/AC-1091

AC-1091: Add Tests for Encounter Repository

---

jitpack.yml

- For Jitpack release
JIRA Issue: https://issues.openmrs.org/browse/AC-1103

AC-1103: Add jitpack.yml

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/DrugRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/AppDatabaseHelper.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/entities/DrugConceptEntity.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/databases/entities/DrugEntity.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/Drug.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/DrugConcept.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/DrugRepositoryTest.kt
openmrs-android-sdk/src/test/resources/mocked_responses/DrugRepository/DrugCreate-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/DrugRepository/DrugGet-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/DrugRepository/DrugGetAll-success.json

- In this PR I have added Unit Tests for the DrugRepository and also fixed some bugs which I realised during Unit Testing
JIRA Issue: https://issues.openmrs.org/browse/AC-1107

AC-1107: Add Unit Tests for DrugRepository and Fix bugs

---

openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/api/repository/ProgramRepository.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/dao/ProgramRoomDAO.kt
openmrs-android-sdk/src/main/java/com/openmrs/android_sdk/library/models/ProgramCreate.kt
openmrs-android-sdk/src/test/java/com/openmrs/android_sdk/library/api/repository/ProgramRepositoryTest.kt
openmrs-android-sdk/src/test/resources/mocked_responses/ProgramRepository/ProgramGet-success.json
openmrs-android-sdk/src/test/resources/mocked_responses/ProgramRepository/ProgramGetAll-success.json

- Added Unit Tests for ProgramRepository and fixed some bugs
JIRA Issue: https://issues.openmrs.org/browse/AC-1108

AC-1108: Add Unit Tests for ProgramRepository and bug fixes
